space: "{{powerops_models}}"
externalId: ShopBasedPartialBidConfiguration
name: ShopBasedPartialBidConfiguration
description: A description of the ShopBasedPartialBidConfiguration
filter:
  and:
    - hasData:
        - type: container
          space: "{{powerops_models}}"
          externalId: PartialShopBased
    - equals:
        property:
          - node
          - space
        value: "{{powerops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          externalId: PartialShopBased
          space: "{{powerops_type_space}}"
implements:
  - space: "{{powerops_models}}"
    externalId: PartialBidConfiguration
    version: "{{version}}"
    type: view
version: "{{version}}"
properties:
  cutOffPrice:
    container:
      space: "{{powerops_models}}"
      externalId: PartialShopBased
      type: container
    containerPropertyIdentifier: cutOffPrice
    name: cutOffPrice
    description: TODO definition
  shopStartSpecification:
    container:
      space: "{{powerops_models}}"
      externalId: PartialShopBased
      type: container
    containerPropertyIdentifier: shopStartSpecification
    name: shopStartSpecification
    description: TODO definition
  shopEndSpecification:
    container:
      space: "{{powerops_models}}"
      externalId: PartialShopBased
      type: container
    containerPropertyIdentifier: shopEndSpecification
    name: shopEndSpecification
    description: TODO definition
  shopBidDateSpecification:
    container:
      space: "{{powerops_models}}"
      externalId: PartialShopBased
      type: container
    containerPropertyIdentifier: shopBidDateSpecification
    name: shopBidDateSpecification
    description: TODO definition
  shopScenarios:
    type:
      space: "{{powerops_type_space}}"
      externalId: PartialShopBased.scenario
    source:
      space: "{{powerops_models}}"
      externalId: Scenario
      version: "{{version}}"
      type: view
    direction: outwards
    name: shopRuns
    description: Configuration of the partial bids that make up the total bid
    connectionType: multi_edge_connection
