space: "{{powerops_models}}"
externalId: WaterValueBasedPartialBidConfiguration
name: WaterValueBasedPartialBidConfiguration
description: A description of the WaterValueBasedPartialBidConfiguration
filter:
  and:
    - hasData:
        - type: container
          space: "{{powerops_models}}"
          externalId: PartialWaterValueBased
    - equals:
        property:
          - node
          - space
        value: "{{powerops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          externalId: PartialWaterValueBased
          space: "{{powerops_type_space}}"
implements:
  - space: "{{powerops_models}}"
    externalId: PartialBidConfiguration
    version: "{{version}}"
    type: view
version: "{{version}}"
properties:
  headLossFactor:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: headLossFactor
    name: headLossFactor
    description: TODO definition
  connectionLosses:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: connectionLosses
    name: connectionLosses
    description: TODO definition
  outletLevel:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: outletLevel
    name: outletLevel
    description: TODO definition
  pMax:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: pMax
    name: pMax
    description: TODO definition
  pMin:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: pMin
    name: pMin
    description: TODO definition
  penstockHeadLossFactors:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: penstockHeadLossFactors
    name: penstockHeadLossFactors
    description: TODO definition
  pMaxTimeSeries:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: pMaxTimeSeries
    name: pMaxTimeSeries
    description: TODO definition
  pMinTimeSeries:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: pMinTimeSeries
    name: pMinTimeSeries
    description: TODO definition
  waterValueTimeSeries:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: waterValueTimeSeries
    name: waterValueTimeSeries
    description: TODO definition
  feedingFeeTimeSeries:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: feedingFeeTimeSeries
    name: feedingFeeTimeSeries
    description: TODO definition
  outletLevelTimeSeries:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: outletLevelTimeSeries
    name: outletLevelTimeSeries
    description: TODO definition
  inletLevelTimeSeries:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: inletLevelTimeSeries
    name: inletLevelTimeSeries
    description: TODO definition
  headDirectTimeSeries:
    container:
      space: "{{powerops_models}}"
      externalId: PartialWaterValueBased
      type: container
    containerPropertyIdentifier: headDirectTimeSeries
    name: headDirectTimeSeries
    description: TODO definition
  generators:
    type:
      space: "{{powerops_type_space}}"
      externalId: GeneratorWaterValueBased.generators
    source:
      space: "{{powerops_models}}"
      externalId: GeneratorWaterValueBased
      version: "{{version}}"
      type: view
    direction: outwards
    name: generators
    description: TODO definition
    connectionType: multi_edge_connection
