[cdf]
default_env = "dev"
default_organization_dir = "toolkit"

[feature_flags]
require-kind = true
edges = true

[modules]
# This is the version of the modules. It should not be changed manually.
# It will be updated by the 'cdf module upgrade' command.
version = "0.3.18"


[plugins]
run = true
pull = false
dump = false
