site_name: PowerOpsSDK
docs_dir: docs
use_directory_urls: false
theme:
  name: material
  features:
    - content.code.copy
    - content.tooltips

nav:
  - Home: ../README.md
  - Tutorials:
      - Quickstart CogShop-as-a-Service: tutorials/quickstart_cogshop_run.ipynb
      - Advanced CogShop-as-a-Service: tutorials/advanced_cogshop_run.ipynb

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: 'pymdownx.superfences.fence_code_format'

plugins:
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True
      include_source: True
  - glightbox:
      width: 100%
      height: auto
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            members_order: source
  - search
