site_name: PowerOpsSDK
docs_dir: docs
use_directory_urls: false
theme:
    name: material
    features:
      - content.code.copy
      - content.tooltips

nav:
    - Home: index.md
    - Notebooks:
      - Shop results: notebooks/shop_results.ipynb
    - Reference:
      - client:
          - SHOP API: packages/client/shop_api.md
          - SHOP API Classes: packages/client/shop_api_classes.md
      - resync:
          - resync: packages/resync/main.md
          - config:
            - main: packages/resync/config/config.md
            - settings: packages/resync/config/settings.md
            - production: packages/resync/config/production.md
            - market: packages/resync/config/market.md
            - cogshop: packages/resync/config/cogshop.md
            - shared: packages/resync/config/shared.md
          - models:
            - Version 1: packages/resync/models/v1.md
            - Version 2: packages/resync/models/v2.md
          - time series mapping: packages/resync/time_series_mapping.md
      - utils:
          - serialization: packages/utils/serialization.md
          - CDF:
            - extraction pipeline: packages/utils/cdf_extraction_pipeline.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''

plugins:
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True
      include_source: True
  - glightbox:
       width: 100%
       height: auto
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            members_order: source
