client:
  project: "${PROJECT}"
  client_name: "power-ops-sdk"
  base_url: "https://${CLUSTER}.cognitedata.com"
  credentials:
    client_credentials:
      token_url: "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
      client_id: "${CLIENT_ID}"
      client_secret: "${CLIENT_SECRET}"
      scopes: ["https://${CLUSTER}.cognitedata.com/.default"]

global:
  max_retries: 10
  max_retry_backoff: 10

power_ops:
  read_dataset: "uc:000:powerops"
  write_dataset: "uc:000:powerops"
  monitor_dataset: "uc:po:monitoring"
