# `client`` is a required section, and it contains the configuration for the Cognite SDK client.
# for more information on what should be included in the client section, see the Cognite SDK documentation.
# https://cognite-sdk-python.readthedocs-hosted.com/en/latest/cognite_client.html#cognite.client.CogniteClient.load
client:
  project: "${PROJECT}"
  client_name: "power-ops-sdk"
  base_url: "https://${CLUSTER}.cognitedata.com"
  credentials:
    client_credentials:
      token_url: "https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
      client_id: "${CLIENT_ID}"
      client_secret: "${CLIENT_SECRET}"
      scopes: ["https://${CLUSTER}.cognitedata.com/.default"]

# `global` is an optional section, and it contains the global configuration for the Cognite SDK client.
# for more information on what should be included in the global section, see the Cognite SDK documentation.
# https://cognite-sdk-python.readthedocs-hosted.com/en/latest/cognite_client.html#cognite.client.config.GlobalConfig.apply_settings
global:
  max_retries: 10
  max_retry_backoff: 10

# `power_ops` is a required section, and it contains the configuration for the PowerOps SDK.
# TODO: remove the datasets from the configuration, as they are not needed anymore.
power_ops:
  read_dataset: "powerops:process"
  write_dataset: "powerops:process"
  monitor_dataset: "powerops:monitor"
