# configure [cognite] sectino in .secrets.toml

[dm_clients]
  space = "CogShop2"
  datamodel = "CogShop2"
  schema_version = 1
  max_tries = 5

[local]
  name = "PowerOpsDm"
  graphql_schema = "cognite/powerops/client/dm/schema.graphql"
  schema_module = "cognite.powerops.client.dm.schema"
