# configure [cognite] and [powerops] sections in .secrets.toml

#[cognite]
#  project = ""
#  cdf_cluster = ""
#  tenant_id = ""
#  client_id = ""
#  client_secret = ""

#[powerops]
#read_dataset = ""
#write_dataset = ""
#cogshop_version = ""

[dm_clients]
  space = "CogShop2"
  datamodel = "CogShop2"
  schema_version = 1
  max_tries = 5

[local]
  name = "PowerOpsDm"
  graphql_schema = "cognite/powerops/client/dm/schema.graphql"
  schema_module = "cognite.powerops.client.dm.schema"
