# Values in .secrets.toml (create it!) will override values in settings.toml.

[cognite]
  login_flow = "interactive"
  project = "power-ops-staging"
  cdf_cluster = "bluefield"
  tenant_id = "431fcc8b-74b8-4171-b7c9-e6fab253913b"
  client_id = "d985b4fe-275e-4df3-9e49-b6b18a77778a"

[powerops]
  read_dataset = "uc:000:powerops"
  write_dataset = "uc:000:powerops"
  monitor_dataset = "uc:po:monitoring"
  cogshop_version = "CogShop2-20231030T120815Z"
  # shop_as_a_service = true
