# Values in .secrets.toml (create it!) will override values in settings.toml.

[cognite]
  login_flow = "interactive"
  project = "power-ops-staging"
  cdf_cluster = "bluefield"
  tenant_id = "431fcc8b-74b8-4171-b7c9-e6fab253913b"
  client_id = "140df241-50bf-4c16-a965-6fd4e5b87958"

[powerops]
  read_dataset = "uc:000:powerops"
  write_dataset = "uc:000:powerops"
  cogshop_version = ""
