space: "{{power_ops_models}}"
externalId: ProductionObligationForBenchmarkingDayAhead
name: ProductionObligationForBenchmarkingDayAhead
description: Production obligations for the day ahead market used in benchmarking
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models}}"
          externalId: ProductionObligationForBenchmarkingDayAhead
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          space: "{{power_ops_type_space}}"
          externalId: ProductionObligationForBenchmarkingDayAhead
implements: []
version: "{{version}}"
properties:
  timeSeries:
    container:
      type: container
      space: '{{power_ops_models}}'
      externalId: ProductionObligationForBenchmarkingDayAhead
    containerPropertyIdentifier: timeSeries
    name: timeSeries
    description: The time series of the day ahead production obligation for benchmarking
  name:
    container:
      type: container
      space: '{{power_ops_models}}'
      externalId: ProductionObligationForBenchmarkingDayAhead
    containerPropertyIdentifier: name
    name: name
    description: The name of the day ahead production obligation for benchmarking
