space: "{{power_ops_models}}"
externalId: DayAheadBenchmarkingConfiguration
name: DayAheadBenchmarkingConfiguration
description: TODO
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models}}"
          externalId: DayAheadBenchmarkingConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          space: "{{power_ops_type_space}}"
          externalId: DayAheadBenchmarkingConfiguration
implements: []
version: "{{version}}"
properties:
  name:
    container:
      space: "{{power_ops_models}}"
      externalId: DayAheadBenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: name
    name: name
    description: The name of the benchmarking configuration
  bidConfigurations:
    container:
      space: "{{power_ops_models}}"
      externalId: DayAheadBenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: bidConfigurations
    name: bidConfigurations
    description: A list of bid configurations used for day ahead benchmarking
  assetsPerShopModel:
    container:
      space: "{{power_ops_models}}"
      externalId: DayAheadBenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: assetsPerShopModel
    name: assetsPerShopModel
    description: TODO
  priceArea:  # TODO: Should we take this from the bidConfigurations?
    container:
      space: "{{power_ops_models}}"
      externalId: DayAheadBenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: priceArea
    name: priceArea
    description: The price area related to the bid calculation task
    source:
      space: "{{power_ops_models}}"
      externalId: PriceAreaDayAhead
      version: "{{version}}"
      type: view
  shopStartSpecification:
    container:
      space: "{{power_ops_models}}"
      externalId: DayAheadBenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: shopStartSpecification
    name: shopStartSpecification
    description: TODO definition
  shopEndSpecification:
    container:
      space: "{{power_ops_models}}"
      externalId: DayAheadBenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: shopEndSpecification
    name: shopEndSpecification
    description: TODO definition