space: "{{power_ops_models}}"
externalId: DayAheadBenchmarkingConfiguration
name: DayAheadBenchmarkingConfiguration
description: TODO
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models}}"
          externalId: BidConfiguration  # TODO: yes?
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          space: "{{power_ops_type_space}}"
          externalId: DayAheadBenchmarkingConfiguration
implements: []
version: "{{version}}"
properties:
  name:
    container:
      space: "{{power_ops_models}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: name
    name: name
    description: The name of the benchmarking configuration
  bidConfigurations:
    type:
      space: "{{power_ops_type_space}}"
      externalId: isSubAssetOf
    source:
      space: "{{power_ops_models}}"
      externalId: BidConfigurationDayAhead_benchmarking
      version: "{{version}}"
      type: view
    direction: outwards
    name: bidConfigurations
    description: A list of bid configurations used for day ahead benchmarking
    connectionType: multi_edge_connection
  assetsPerShopModel:
    type:
      space: "{{power_ops_type_space}}"
      externalId: isSubAssetOf
    source:
      space: "{{power_ops_models}}"
      externalId: ShopModelToAssets
      version: "{{version}}"
      type: view
    direction: outwards
    name: assetsPerShopModel
    description: TODO
    connectionType: multi_edge_connection
  priceArea:  # TODO: Should we take this from the bidConfigurations?
    container:
      space: "{{power_ops_models}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: priceArea
    name: priceArea
    description: The price area related to the bid calculation task
    source:
      space: "{{power_ops_models}}"
      externalId: PriceAreaDayAhead
      version: "{{version}}"
      type: view
  shopStartSpecification:
    container:
      space: "{{power_ops_models}}"
      externalId: ShopScenarioSet  # TODO: Ok to use this container?
      type: container
    containerPropertyIdentifier: startSpecification
    name: startSpecification
    description: TODO definition
  shopEndSpecification:
    container:
      space: "{{power_ops_models}}"
      externalId: ShopScenarioSet  # TODO: Ok to use this container?
      type: container
    containerPropertyIdentifier: endSpecification
    name: endSpecification
    description: TODO definition