space: "{{powerops_models}}"
externalId: MarketConfiguration
name: MarketConfiguration
description: Market configuration
filter:
  and:
    - hasData:
        - type: container
          space: "{{powerops_models}}"
          externalId: MarketConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{powerops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          externalId: MarketConfiguration
          space: "{{powerops_type_space}}"
implements: []
version: "{{version}}"
properties:
  name:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: name
    name: name
    description: The name of the market
  maxPrice:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: maxPrice
    name: maxPrice
  minPrice:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: minPrice
    name: minPrice
  timeZone:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: timeZone
    name: timeZone
  priceUnit:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: priceUnit
    name: priceUnit
  priceSteps:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: priceSteps
    name: priceSteps
  tickSize:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: tickSize
    name: tickSize
  timeUnit:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: timeUnit
    name: timeUnit
  tradeLot:
    container:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      type: container
    containerPropertyIdentifier: tradeLot
    name: tradeLot
