# Only valid for this module, loads template variables from environment

data_model: fin_test
space: testing
data_set: testing
data_set_desc: Testing

model_space: testing
instance_space: testing

# versions:
data_model_version: '1'

view_Alert_version: '1'

view_BidMethod_version: '1'
view_SHOP_version: '1'
view_WaterValueBased_version: '1'

view_MarketPriceArea_version: '1'

view_BidTable_version: '1'
view_SHOPTable_version: '1'

view_ProductionPricePair_version: '1'

view_Bid_version: '1'


# auth:
clientId: ${IDP_CLIENT_ID}
clientSecret: ${IDP_CLIENT_SECRET}
tokenUri: ${IDP_TOKEN_URL}
# Optional: If idP requires providing the scopes
cdfProjectName: ${CDF_PROJECT}
scopes: ${IDP_SCOPES}
# Optional: If idP requires providing the audience
audience: ${IDP_AUDIENCE}
