# Path to the working directory where the data model and files are stored
working_directory: "resync"
# Path to the directory where the data model node and edge files are stored
toolkit_directory: "toolkit/modules/resync/data_models/nodes"
# If set to true, properties with None values will be skipped and not written to the data model files.
# This is useful to get more concise toolkit deploy dry run verbose output, so it's recommended when using verbose mode.
ignore_nones: true
# The following variables are used to replace placeholders in the data model files.
instance_space: "power_ops_instances"
models_space: "power_ops_core"
type_space: "power_ops_types"
data_model_version: "1"

# Purge configuration
toolkit_modules:
  - "toolkit/modules/resync/data_models/nodes"
