# Path to the working directory where the data model and files are stored
working_directory: "resync"
# Path to the directory where the data model node and edge files are stored
toolkit_directory: "toolkit/modules/resync/data_models/nodes"
# If set to true, properties with None values will be skipped and not written to the data model files.
# This is useful to get more concise toolkit deploy dry run verbose output, so it's recommended when using verbose mode.
ignore_nones: true
# The following variables are used to replace placeholders in the data model files.
instance_space: "power_ops_instances"
models_space: "power_ops_core"
type_space: "power_ops_types"
data_model_version: "1"

# Purge configuration
toolkit_modules:
  - "toolkit/modules/resync/data_models/nodes"
# The type of nodes to exclude from deletion, if the node type doesn't have any edges you shouldn't need to add any
# types to the `exclude_edges` list.
exclude_nodes:
  - "ShopFile"
  - "ShopScenario"
# The type of edges to exclude from deletion, recommended to only exclude edge types based on excluding the relevant node
exclude_edges: []
# NOTE: resync does not handle clean up of edges tied to toolkit "owned" nodes if you've excluded the type as resync doesn't
# have a way to categorize edges/nodes by resourced "owned" or "not owned" by toolkit
