space: "{{power_ops_models}}"
externalId: BenchmarkingConfigurationDayAhead
name: BenchmarkingConfigurationDayAhead
description: Representing the same as the good old benchmarking config asset
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models}}"
          externalId: BenchmarkingConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          space: "{{power_ops_type_space}}"
          externalId: BenchmarkingConfigurationDayAhead
implements: []
version: "{{version}}"
properties:
  name:
    container:
      space: "{{power_ops_models}}"
      externalId: BenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: name
    name: name
    description: The name of the benchmarking configuration
  bidConfigurations:
    type:
      space: "{{power_ops_type_space}}"
      externalId: benchmarkingBidConfigurations
    source:
      space: "{{power_ops_models}}"
      externalId: BidConfigurationDayAhead
      version: "{{version}}"
      type: view
    direction: outwards
    name: bidConfigurations
    description: Benchmarking workflow will benchmark (i. e. run SHOP for obligation based on) all BidDocuments generated by these methods
    connectionType: multi_edge_connection
  assetsPerShopModel:
    type:
      space: "{{power_ops_type_space}}"
      externalId: assetsPerShopModel
    source:
      space: "{{power_ops_models}}"
      externalId: ShopModelWithAssets
      version: "{{version}}"
      type: view
    direction: outwards
    name: assetsPerShopModel
    description: The SHOP models to be used for benchmarking of these bid configurations (should be all SHOP models needed to 'cover' the price area)
    connectionType: multi_edge_connection
  priceArea: # TODO: Should we take this from the bidConfigurations?
    container:
      space: "{{power_ops_models}}"
      externalId: BenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: priceArea
    name: priceArea
    description: The price area related to the bid calculation task
    source:
      space: "{{power_ops_models}}"
      externalId: PriceAreaDayAhead
      version: "{{version}}"
      type: view
  shopStartSpecification:
    container:
      space: "{{power_ops_models}}"
      externalId: BenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: shopStartSpecification
    name: shopStartSpecification
    description: Relative time spec. for start-time for benchmarking SHOP runs
    source:
      space: "{{power_ops_models}}"
      externalId: DateSpecification
      version: "{{version}}"
      type: view
  shopEndSpecification:
    container:
      space: "{{power_ops_models}}"
      externalId: BenchmarkingConfiguration
      type: container
    containerPropertyIdentifier: shopEndSpecification
    name: shopEndSpecification
    description: Relative time spec. for end-time for benchmarking SHOP runs
    source:
      space: "{{power_ops_models}}"
      externalId: DateSpecification
      version: "{{version}}"
      type: view
