from ._core import (
    DataRecord,
    DataRecordWrite,
    DomainModel,
    DomainModelCore,
    DomainModelWrite,
    DomainModelList,
    DomainRelationWrite,
    ResourcesWrite,
    ResourcesWriteResult,
)
from ._alert import (
    Alert,
    AlertApply,
    AlertApplyList,
    AlertFields,
    AlertList,
    AlertTextFields,
    AlertWrite,
    AlertWriteList,
)
from ._bid_configuration import (
    BidConfiguration,
    BidConfigurationApply,
    BidConfigurationApplyList,
    BidConfigurationFields,
    BidConfigurationList,
    BidConfigurationTextFields,
    BidConfigurationWrite,
    BidConfigurationWriteList,
)
from ._bid_document import (
    BidDocument,
    BidDocumentApply,
    BidDocumentApplyList,
    BidDocumentFields,
    BidDocumentList,
    BidDocumentTextFields,
    BidDocumentWrite,
    BidDocumentWriteList,
)
from ._bid_document_afrr import (
    BidDocumentAFRR,
    BidDocumentAFRRApply,
    BidDocumentAFRRApplyList,
    BidDocumentAFRRFields,
    BidDocumentAFRRList,
    BidDocumentAFRRTextFields,
    BidDocumentAFRRWrite,
    BidDocumentAFRRWriteList,
)
from ._bid_document_day_ahead import (
    BidDocumentDayAhead,
    BidDocumentDayAheadApply,
    BidDocumentDayAheadApplyList,
    BidDocumentDayAheadFields,
    BidDocumentDayAheadList,
    BidDocumentDayAheadTextFields,
    BidDocumentDayAheadWrite,
    BidDocumentDayAheadWriteList,
)
from ._bid_matrix import (
    BidMatrix,
    BidMatrixApply,
    BidMatrixApplyList,
    BidMatrixFields,
    BidMatrixList,
    BidMatrixTextFields,
    BidMatrixWrite,
    BidMatrixWriteList,
)
from ._bid_row import (
    BidRow,
    BidRowApply,
    BidRowApplyList,
    BidRowFields,
    BidRowList,
    BidRowTextFields,
    BidRowWrite,
    BidRowWriteList,
)
from ._case import Case, CaseApply, CaseApplyList, CaseFields, CaseList, CaseWrite, CaseWriteList
from ._commands import (
    Commands,
    CommandsApply,
    CommandsApplyList,
    CommandsFields,
    CommandsList,
    CommandsTextFields,
    CommandsWrite,
    CommandsWriteList,
)
from ._function_input import (
    FunctionInput,
    FunctionInputApply,
    FunctionInputApplyList,
    FunctionInputFields,
    FunctionInputList,
    FunctionInputTextFields,
    FunctionInputWrite,
    FunctionInputWriteList,
)
from ._function_output import (
    FunctionOutput,
    FunctionOutputApply,
    FunctionOutputApplyList,
    FunctionOutputFields,
    FunctionOutputList,
    FunctionOutputTextFields,
    FunctionOutputWrite,
    FunctionOutputWriteList,
)
from ._generator import (
    Generator,
    GeneratorApply,
    GeneratorApplyList,
    GeneratorFields,
    GeneratorList,
    GeneratorTextFields,
    GeneratorWrite,
    GeneratorWriteList,
)
from ._generator_efficiency_curve import (
    GeneratorEfficiencyCurve,
    GeneratorEfficiencyCurveApply,
    GeneratorEfficiencyCurveApplyList,
    GeneratorEfficiencyCurveFields,
    GeneratorEfficiencyCurveList,
    GeneratorEfficiencyCurveWrite,
    GeneratorEfficiencyCurveWriteList,
)
from ._mapping import (
    Mapping,
    MappingApply,
    MappingApplyList,
    MappingFields,
    MappingList,
    MappingTextFields,
    MappingWrite,
    MappingWriteList,
)
from ._market_configuration import (
    MarketConfiguration,
    MarketConfigurationApply,
    MarketConfigurationApplyList,
    MarketConfigurationFields,
    MarketConfigurationList,
    MarketConfigurationTextFields,
    MarketConfigurationWrite,
    MarketConfigurationWriteList,
)
from ._model_template import (
    ModelTemplate,
    ModelTemplateApply,
    ModelTemplateApplyList,
    ModelTemplateFields,
    ModelTemplateList,
    ModelTemplateTextFields,
    ModelTemplateWrite,
    ModelTemplateWriteList,
)
from ._partial_bid_configuration import (
    PartialBidConfiguration,
    PartialBidConfigurationApply,
    PartialBidConfigurationApplyList,
    PartialBidConfigurationFields,
    PartialBidConfigurationList,
    PartialBidConfigurationTextFields,
    PartialBidConfigurationWrite,
    PartialBidConfigurationWriteList,
)
from ._partial_bid_matrix_calculation_input import (
    PartialBidMatrixCalculationInput,
    PartialBidMatrixCalculationInputApply,
    PartialBidMatrixCalculationInputApplyList,
    PartialBidMatrixCalculationInputFields,
    PartialBidMatrixCalculationInputList,
    PartialBidMatrixCalculationInputTextFields,
    PartialBidMatrixCalculationInputWrite,
    PartialBidMatrixCalculationInputWriteList,
)
from ._partial_bid_matrix_calculation_output import (
    PartialBidMatrixCalculationOutput,
    PartialBidMatrixCalculationOutputApply,
    PartialBidMatrixCalculationOutputApplyList,
    PartialBidMatrixCalculationOutputFields,
    PartialBidMatrixCalculationOutputList,
    PartialBidMatrixCalculationOutputTextFields,
    PartialBidMatrixCalculationOutputWrite,
    PartialBidMatrixCalculationOutputWriteList,
)
from ._plant import (
    Plant,
    PlantApply,
    PlantApplyList,
    PlantFields,
    PlantList,
    PlantTextFields,
    PlantWrite,
    PlantWriteList,
)
from ._power_asset import (
    PowerAsset,
    PowerAssetApply,
    PowerAssetApplyList,
    PowerAssetFields,
    PowerAssetList,
    PowerAssetTextFields,
    PowerAssetWrite,
    PowerAssetWriteList,
)
from ._preprocessor_input import (
    PreprocessorInput,
    PreprocessorInputApply,
    PreprocessorInputApplyList,
    PreprocessorInputFields,
    PreprocessorInputList,
    PreprocessorInputTextFields,
    PreprocessorInputWrite,
    PreprocessorInputWriteList,
)
from ._preprocessor_output import (
    PreprocessorOutput,
    PreprocessorOutputApply,
    PreprocessorOutputApplyList,
    PreprocessorOutputFields,
    PreprocessorOutputList,
    PreprocessorOutputTextFields,
    PreprocessorOutputWrite,
    PreprocessorOutputWriteList,
)
from ._price_area import (
    PriceArea,
    PriceAreaApply,
    PriceAreaApplyList,
    PriceAreaFields,
    PriceAreaList,
    PriceAreaTextFields,
    PriceAreaWrite,
    PriceAreaWriteList,
)
from ._price_area_afrr import (
    PriceAreaAFRR,
    PriceAreaAFRRApply,
    PriceAreaAFRRApplyList,
    PriceAreaAFRRFields,
    PriceAreaAFRRList,
    PriceAreaAFRRTextFields,
    PriceAreaAFRRWrite,
    PriceAreaAFRRWriteList,
)
from ._price_production import (
    PriceProduction,
    PriceProductionApply,
    PriceProductionApplyList,
    PriceProductionFields,
    PriceProductionList,
    PriceProductionWrite,
    PriceProductionWriteList,
)
from ._shop_result import (
    SHOPResult,
    SHOPResultApply,
    SHOPResultApplyList,
    SHOPResultFields,
    SHOPResultList,
    SHOPResultWrite,
    SHOPResultWriteList,
)
from ._shop_time_series import (
    SHOPTimeSeries,
    SHOPTimeSeriesApply,
    SHOPTimeSeriesApplyList,
    SHOPTimeSeriesFields,
    SHOPTimeSeriesList,
    SHOPTimeSeriesTextFields,
    SHOPTimeSeriesWrite,
    SHOPTimeSeriesWriteList,
)
from ._shop_trigger_input import (
    SHOPTriggerInput,
    SHOPTriggerInputApply,
    SHOPTriggerInputApplyList,
    SHOPTriggerInputFields,
    SHOPTriggerInputList,
    SHOPTriggerInputTextFields,
    SHOPTriggerInputWrite,
    SHOPTriggerInputWriteList,
)
from ._shop_trigger_output import (
    SHOPTriggerOutput,
    SHOPTriggerOutputApply,
    SHOPTriggerOutputApplyList,
    SHOPTriggerOutputFields,
    SHOPTriggerOutputList,
    SHOPTriggerOutputTextFields,
    SHOPTriggerOutputWrite,
    SHOPTriggerOutputWriteList,
)
from ._scenario import (
    Scenario,
    ScenarioApply,
    ScenarioApplyList,
    ScenarioFields,
    ScenarioList,
    ScenarioTextFields,
    ScenarioWrite,
    ScenarioWriteList,
)
from ._scenario_set import (
    ScenarioSet,
    ScenarioSetApply,
    ScenarioSetApplyList,
    ScenarioSetFields,
    ScenarioSetList,
    ScenarioSetTextFields,
    ScenarioSetWrite,
    ScenarioSetWriteList,
)
from ._shop_based_partial_bid_configuration import (
    ShopBasedPartialBidConfiguration,
    ShopBasedPartialBidConfigurationApply,
    ShopBasedPartialBidConfigurationApplyList,
    ShopBasedPartialBidConfigurationFields,
    ShopBasedPartialBidConfigurationList,
    ShopBasedPartialBidConfigurationTextFields,
    ShopBasedPartialBidConfigurationWrite,
    ShopBasedPartialBidConfigurationWriteList,
)
from ._shop_partial_bid_matrix_calculation_input import (
    ShopPartialBidMatrixCalculationInput,
    ShopPartialBidMatrixCalculationInputApply,
    ShopPartialBidMatrixCalculationInputApplyList,
    ShopPartialBidMatrixCalculationInputFields,
    ShopPartialBidMatrixCalculationInputList,
    ShopPartialBidMatrixCalculationInputTextFields,
    ShopPartialBidMatrixCalculationInputWrite,
    ShopPartialBidMatrixCalculationInputWriteList,
)
from ._task_dispatcher_input import (
    TaskDispatcherInput,
    TaskDispatcherInputApply,
    TaskDispatcherInputApplyList,
    TaskDispatcherInputFields,
    TaskDispatcherInputList,
    TaskDispatcherInputTextFields,
    TaskDispatcherInputWrite,
    TaskDispatcherInputWriteList,
)
from ._task_dispatcher_output import (
    TaskDispatcherOutput,
    TaskDispatcherOutputApply,
    TaskDispatcherOutputApplyList,
    TaskDispatcherOutputFields,
    TaskDispatcherOutputList,
    TaskDispatcherOutputTextFields,
    TaskDispatcherOutputWrite,
    TaskDispatcherOutputWriteList,
)
from ._total_bid_matrix_calculation_input import (
    TotalBidMatrixCalculationInput,
    TotalBidMatrixCalculationInputApply,
    TotalBidMatrixCalculationInputApplyList,
    TotalBidMatrixCalculationInputFields,
    TotalBidMatrixCalculationInputList,
    TotalBidMatrixCalculationInputTextFields,
    TotalBidMatrixCalculationInputWrite,
    TotalBidMatrixCalculationInputWriteList,
)
from ._total_bid_matrix_calculation_output import (
    TotalBidMatrixCalculationOutput,
    TotalBidMatrixCalculationOutputApply,
    TotalBidMatrixCalculationOutputApplyList,
    TotalBidMatrixCalculationOutputFields,
    TotalBidMatrixCalculationOutputList,
    TotalBidMatrixCalculationOutputTextFields,
    TotalBidMatrixCalculationOutputWrite,
    TotalBidMatrixCalculationOutputWriteList,
)
from ._turbine_efficiency_curve import (
    TurbineEfficiencyCurve,
    TurbineEfficiencyCurveApply,
    TurbineEfficiencyCurveApplyList,
    TurbineEfficiencyCurveFields,
    TurbineEfficiencyCurveList,
    TurbineEfficiencyCurveWrite,
    TurbineEfficiencyCurveWriteList,
)
from ._water_value_based_partial_bid_configuration import (
    WaterValueBasedPartialBidConfiguration,
    WaterValueBasedPartialBidConfigurationApply,
    WaterValueBasedPartialBidConfigurationApplyList,
    WaterValueBasedPartialBidConfigurationFields,
    WaterValueBasedPartialBidConfigurationList,
    WaterValueBasedPartialBidConfigurationTextFields,
    WaterValueBasedPartialBidConfigurationWrite,
    WaterValueBasedPartialBidConfigurationWriteList,
)
from ._water_value_based_partial_bid_matrix_calculation_input import (
    WaterValueBasedPartialBidMatrixCalculationInput,
    WaterValueBasedPartialBidMatrixCalculationInputApply,
    WaterValueBasedPartialBidMatrixCalculationInputApplyList,
    WaterValueBasedPartialBidMatrixCalculationInputFields,
    WaterValueBasedPartialBidMatrixCalculationInputList,
    WaterValueBasedPartialBidMatrixCalculationInputTextFields,
    WaterValueBasedPartialBidMatrixCalculationInputWrite,
    WaterValueBasedPartialBidMatrixCalculationInputWriteList,
)

BidConfiguration.model_rebuild()
BidConfigurationWrite.model_rebuild()
BidConfigurationApply.model_rebuild()
BidDocument.model_rebuild()
BidDocumentWrite.model_rebuild()
BidDocumentApply.model_rebuild()
BidDocumentAFRR.model_rebuild()
BidDocumentAFRRWrite.model_rebuild()
BidDocumentAFRRApply.model_rebuild()
BidDocumentDayAhead.model_rebuild()
BidDocumentDayAheadWrite.model_rebuild()
BidDocumentDayAheadApply.model_rebuild()
BidMatrix.model_rebuild()
BidMatrixWrite.model_rebuild()
BidMatrixApply.model_rebuild()
BidRow.model_rebuild()
BidRowWrite.model_rebuild()
BidRowApply.model_rebuild()
Case.model_rebuild()
CaseWrite.model_rebuild()
CaseApply.model_rebuild()
FunctionOutput.model_rebuild()
FunctionOutputWrite.model_rebuild()
FunctionOutputApply.model_rebuild()
Generator.model_rebuild()
GeneratorWrite.model_rebuild()
GeneratorApply.model_rebuild()
ModelTemplate.model_rebuild()
ModelTemplateWrite.model_rebuild()
ModelTemplateApply.model_rebuild()
PartialBidMatrixCalculationInput.model_rebuild()
PartialBidMatrixCalculationInputWrite.model_rebuild()
PartialBidMatrixCalculationInputApply.model_rebuild()
PartialBidMatrixCalculationOutput.model_rebuild()
PartialBidMatrixCalculationOutputWrite.model_rebuild()
PartialBidMatrixCalculationOutputApply.model_rebuild()
Plant.model_rebuild()
PlantWrite.model_rebuild()
PlantApply.model_rebuild()
PreprocessorInput.model_rebuild()
PreprocessorInputWrite.model_rebuild()
PreprocessorInputApply.model_rebuild()
PreprocessorOutput.model_rebuild()
PreprocessorOutputWrite.model_rebuild()
PreprocessorOutputApply.model_rebuild()
PriceProduction.model_rebuild()
PriceProductionWrite.model_rebuild()
PriceProductionApply.model_rebuild()
SHOPResult.model_rebuild()
SHOPResultWrite.model_rebuild()
SHOPResultApply.model_rebuild()
SHOPTriggerInput.model_rebuild()
SHOPTriggerInputWrite.model_rebuild()
SHOPTriggerInputApply.model_rebuild()
SHOPTriggerOutput.model_rebuild()
SHOPTriggerOutputWrite.model_rebuild()
SHOPTriggerOutputApply.model_rebuild()
Scenario.model_rebuild()
ScenarioWrite.model_rebuild()
ScenarioApply.model_rebuild()
ScenarioSet.model_rebuild()
ScenarioSetWrite.model_rebuild()
ScenarioSetApply.model_rebuild()
ShopBasedPartialBidConfiguration.model_rebuild()
ShopBasedPartialBidConfigurationWrite.model_rebuild()
ShopBasedPartialBidConfigurationApply.model_rebuild()
ShopPartialBidMatrixCalculationInput.model_rebuild()
ShopPartialBidMatrixCalculationInputWrite.model_rebuild()
ShopPartialBidMatrixCalculationInputApply.model_rebuild()
TaskDispatcherInput.model_rebuild()
TaskDispatcherInputWrite.model_rebuild()
TaskDispatcherInputApply.model_rebuild()
TaskDispatcherOutput.model_rebuild()
TaskDispatcherOutputWrite.model_rebuild()
TaskDispatcherOutputApply.model_rebuild()
TotalBidMatrixCalculationInput.model_rebuild()
TotalBidMatrixCalculationInputWrite.model_rebuild()
TotalBidMatrixCalculationInputApply.model_rebuild()
TotalBidMatrixCalculationOutput.model_rebuild()
TotalBidMatrixCalculationOutputWrite.model_rebuild()
TotalBidMatrixCalculationOutputApply.model_rebuild()
WaterValueBasedPartialBidConfiguration.model_rebuild()
WaterValueBasedPartialBidConfigurationWrite.model_rebuild()
WaterValueBasedPartialBidConfigurationApply.model_rebuild()
WaterValueBasedPartialBidMatrixCalculationInput.model_rebuild()
WaterValueBasedPartialBidMatrixCalculationInputWrite.model_rebuild()
WaterValueBasedPartialBidMatrixCalculationInputApply.model_rebuild()

__all__ = [
    "DataRecord",
    "DataRecordWrite",
    "ResourcesWrite",
    "DomainModel",
    "DomainModelCore",
    "DomainModelWrite",
    "DomainModelList",
    "DomainRelationWrite",
    "ResourcesWriteResult",
    "Alert",
    "AlertWrite",
    "AlertApply",
    "AlertList",
    "AlertWriteList",
    "AlertApplyList",
    "AlertFields",
    "AlertTextFields",
    "BidConfiguration",
    "BidConfigurationWrite",
    "BidConfigurationApply",
    "BidConfigurationList",
    "BidConfigurationWriteList",
    "BidConfigurationApplyList",
    "BidConfigurationFields",
    "BidConfigurationTextFields",
    "BidDocument",
    "BidDocumentWrite",
    "BidDocumentApply",
    "BidDocumentList",
    "BidDocumentWriteList",
    "BidDocumentApplyList",
    "BidDocumentFields",
    "BidDocumentTextFields",
    "BidDocumentAFRR",
    "BidDocumentAFRRWrite",
    "BidDocumentAFRRApply",
    "BidDocumentAFRRList",
    "BidDocumentAFRRWriteList",
    "BidDocumentAFRRApplyList",
    "BidDocumentAFRRFields",
    "BidDocumentAFRRTextFields",
    "BidDocumentDayAhead",
    "BidDocumentDayAheadWrite",
    "BidDocumentDayAheadApply",
    "BidDocumentDayAheadList",
    "BidDocumentDayAheadWriteList",
    "BidDocumentDayAheadApplyList",
    "BidDocumentDayAheadFields",
    "BidDocumentDayAheadTextFields",
    "BidMatrix",
    "BidMatrixWrite",
    "BidMatrixApply",
    "BidMatrixList",
    "BidMatrixWriteList",
    "BidMatrixApplyList",
    "BidMatrixFields",
    "BidMatrixTextFields",
    "BidRow",
    "BidRowWrite",
    "BidRowApply",
    "BidRowList",
    "BidRowWriteList",
    "BidRowApplyList",
    "BidRowFields",
    "BidRowTextFields",
    "Case",
    "CaseWrite",
    "CaseApply",
    "CaseList",
    "CaseWriteList",
    "CaseApplyList",
    "CaseFields",
    "Commands",
    "CommandsWrite",
    "CommandsApply",
    "CommandsList",
    "CommandsWriteList",
    "CommandsApplyList",
    "CommandsFields",
    "CommandsTextFields",
    "FunctionInput",
    "FunctionInputWrite",
    "FunctionInputApply",
    "FunctionInputList",
    "FunctionInputWriteList",
    "FunctionInputApplyList",
    "FunctionInputFields",
    "FunctionInputTextFields",
    "FunctionOutput",
    "FunctionOutputWrite",
    "FunctionOutputApply",
    "FunctionOutputList",
    "FunctionOutputWriteList",
    "FunctionOutputApplyList",
    "FunctionOutputFields",
    "FunctionOutputTextFields",
    "Generator",
    "GeneratorWrite",
    "GeneratorApply",
    "GeneratorList",
    "GeneratorWriteList",
    "GeneratorApplyList",
    "GeneratorFields",
    "GeneratorTextFields",
    "GeneratorEfficiencyCurve",
    "GeneratorEfficiencyCurveWrite",
    "GeneratorEfficiencyCurveApply",
    "GeneratorEfficiencyCurveList",
    "GeneratorEfficiencyCurveWriteList",
    "GeneratorEfficiencyCurveApplyList",
    "GeneratorEfficiencyCurveFields",
    "Mapping",
    "MappingWrite",
    "MappingApply",
    "MappingList",
    "MappingWriteList",
    "MappingApplyList",
    "MappingFields",
    "MappingTextFields",
    "MarketConfiguration",
    "MarketConfigurationWrite",
    "MarketConfigurationApply",
    "MarketConfigurationList",
    "MarketConfigurationWriteList",
    "MarketConfigurationApplyList",
    "MarketConfigurationFields",
    "MarketConfigurationTextFields",
    "ModelTemplate",
    "ModelTemplateWrite",
    "ModelTemplateApply",
    "ModelTemplateList",
    "ModelTemplateWriteList",
    "ModelTemplateApplyList",
    "ModelTemplateFields",
    "ModelTemplateTextFields",
    "PartialBidConfiguration",
    "PartialBidConfigurationWrite",
    "PartialBidConfigurationApply",
    "PartialBidConfigurationList",
    "PartialBidConfigurationWriteList",
    "PartialBidConfigurationApplyList",
    "PartialBidConfigurationFields",
    "PartialBidConfigurationTextFields",
    "PartialBidMatrixCalculationInput",
    "PartialBidMatrixCalculationInputWrite",
    "PartialBidMatrixCalculationInputApply",
    "PartialBidMatrixCalculationInputList",
    "PartialBidMatrixCalculationInputWriteList",
    "PartialBidMatrixCalculationInputApplyList",
    "PartialBidMatrixCalculationInputFields",
    "PartialBidMatrixCalculationInputTextFields",
    "PartialBidMatrixCalculationOutput",
    "PartialBidMatrixCalculationOutputWrite",
    "PartialBidMatrixCalculationOutputApply",
    "PartialBidMatrixCalculationOutputList",
    "PartialBidMatrixCalculationOutputWriteList",
    "PartialBidMatrixCalculationOutputApplyList",
    "PartialBidMatrixCalculationOutputFields",
    "PartialBidMatrixCalculationOutputTextFields",
    "Plant",
    "PlantWrite",
    "PlantApply",
    "PlantList",
    "PlantWriteList",
    "PlantApplyList",
    "PlantFields",
    "PlantTextFields",
    "PowerAsset",
    "PowerAssetWrite",
    "PowerAssetApply",
    "PowerAssetList",
    "PowerAssetWriteList",
    "PowerAssetApplyList",
    "PowerAssetFields",
    "PowerAssetTextFields",
    "PreprocessorInput",
    "PreprocessorInputWrite",
    "PreprocessorInputApply",
    "PreprocessorInputList",
    "PreprocessorInputWriteList",
    "PreprocessorInputApplyList",
    "PreprocessorInputFields",
    "PreprocessorInputTextFields",
    "PreprocessorOutput",
    "PreprocessorOutputWrite",
    "PreprocessorOutputApply",
    "PreprocessorOutputList",
    "PreprocessorOutputWriteList",
    "PreprocessorOutputApplyList",
    "PreprocessorOutputFields",
    "PreprocessorOutputTextFields",
    "PriceArea",
    "PriceAreaWrite",
    "PriceAreaApply",
    "PriceAreaList",
    "PriceAreaWriteList",
    "PriceAreaApplyList",
    "PriceAreaFields",
    "PriceAreaTextFields",
    "PriceAreaAFRR",
    "PriceAreaAFRRWrite",
    "PriceAreaAFRRApply",
    "PriceAreaAFRRList",
    "PriceAreaAFRRWriteList",
    "PriceAreaAFRRApplyList",
    "PriceAreaAFRRFields",
    "PriceAreaAFRRTextFields",
    "PriceProduction",
    "PriceProductionWrite",
    "PriceProductionApply",
    "PriceProductionList",
    "PriceProductionWriteList",
    "PriceProductionApplyList",
    "PriceProductionFields",
    "SHOPResult",
    "SHOPResultWrite",
    "SHOPResultApply",
    "SHOPResultList",
    "SHOPResultWriteList",
    "SHOPResultApplyList",
    "SHOPResultFields",
    "SHOPTimeSeries",
    "SHOPTimeSeriesWrite",
    "SHOPTimeSeriesApply",
    "SHOPTimeSeriesList",
    "SHOPTimeSeriesWriteList",
    "SHOPTimeSeriesApplyList",
    "SHOPTimeSeriesFields",
    "SHOPTimeSeriesTextFields",
    "SHOPTriggerInput",
    "SHOPTriggerInputWrite",
    "SHOPTriggerInputApply",
    "SHOPTriggerInputList",
    "SHOPTriggerInputWriteList",
    "SHOPTriggerInputApplyList",
    "SHOPTriggerInputFields",
    "SHOPTriggerInputTextFields",
    "SHOPTriggerOutput",
    "SHOPTriggerOutputWrite",
    "SHOPTriggerOutputApply",
    "SHOPTriggerOutputList",
    "SHOPTriggerOutputWriteList",
    "SHOPTriggerOutputApplyList",
    "SHOPTriggerOutputFields",
    "SHOPTriggerOutputTextFields",
    "Scenario",
    "ScenarioWrite",
    "ScenarioApply",
    "ScenarioList",
    "ScenarioWriteList",
    "ScenarioApplyList",
    "ScenarioFields",
    "ScenarioTextFields",
    "ScenarioSet",
    "ScenarioSetWrite",
    "ScenarioSetApply",
    "ScenarioSetList",
    "ScenarioSetWriteList",
    "ScenarioSetApplyList",
    "ScenarioSetFields",
    "ScenarioSetTextFields",
    "ShopBasedPartialBidConfiguration",
    "ShopBasedPartialBidConfigurationWrite",
    "ShopBasedPartialBidConfigurationApply",
    "ShopBasedPartialBidConfigurationList",
    "ShopBasedPartialBidConfigurationWriteList",
    "ShopBasedPartialBidConfigurationApplyList",
    "ShopBasedPartialBidConfigurationFields",
    "ShopBasedPartialBidConfigurationTextFields",
    "ShopPartialBidMatrixCalculationInput",
    "ShopPartialBidMatrixCalculationInputWrite",
    "ShopPartialBidMatrixCalculationInputApply",
    "ShopPartialBidMatrixCalculationInputList",
    "ShopPartialBidMatrixCalculationInputWriteList",
    "ShopPartialBidMatrixCalculationInputApplyList",
    "ShopPartialBidMatrixCalculationInputFields",
    "ShopPartialBidMatrixCalculationInputTextFields",
    "TaskDispatcherInput",
    "TaskDispatcherInputWrite",
    "TaskDispatcherInputApply",
    "TaskDispatcherInputList",
    "TaskDispatcherInputWriteList",
    "TaskDispatcherInputApplyList",
    "TaskDispatcherInputFields",
    "TaskDispatcherInputTextFields",
    "TaskDispatcherOutput",
    "TaskDispatcherOutputWrite",
    "TaskDispatcherOutputApply",
    "TaskDispatcherOutputList",
    "TaskDispatcherOutputWriteList",
    "TaskDispatcherOutputApplyList",
    "TaskDispatcherOutputFields",
    "TaskDispatcherOutputTextFields",
    "TotalBidMatrixCalculationInput",
    "TotalBidMatrixCalculationInputWrite",
    "TotalBidMatrixCalculationInputApply",
    "TotalBidMatrixCalculationInputList",
    "TotalBidMatrixCalculationInputWriteList",
    "TotalBidMatrixCalculationInputApplyList",
    "TotalBidMatrixCalculationInputFields",
    "TotalBidMatrixCalculationInputTextFields",
    "TotalBidMatrixCalculationOutput",
    "TotalBidMatrixCalculationOutputWrite",
    "TotalBidMatrixCalculationOutputApply",
    "TotalBidMatrixCalculationOutputList",
    "TotalBidMatrixCalculationOutputWriteList",
    "TotalBidMatrixCalculationOutputApplyList",
    "TotalBidMatrixCalculationOutputFields",
    "TotalBidMatrixCalculationOutputTextFields",
    "TurbineEfficiencyCurve",
    "TurbineEfficiencyCurveWrite",
    "TurbineEfficiencyCurveApply",
    "TurbineEfficiencyCurveList",
    "TurbineEfficiencyCurveWriteList",
    "TurbineEfficiencyCurveApplyList",
    "TurbineEfficiencyCurveFields",
    "WaterValueBasedPartialBidConfiguration",
    "WaterValueBasedPartialBidConfigurationWrite",
    "WaterValueBasedPartialBidConfigurationApply",
    "WaterValueBasedPartialBidConfigurationList",
    "WaterValueBasedPartialBidConfigurationWriteList",
    "WaterValueBasedPartialBidConfigurationApplyList",
    "WaterValueBasedPartialBidConfigurationFields",
    "WaterValueBasedPartialBidConfigurationTextFields",
    "WaterValueBasedPartialBidMatrixCalculationInput",
    "WaterValueBasedPartialBidMatrixCalculationInputWrite",
    "WaterValueBasedPartialBidMatrixCalculationInputApply",
    "WaterValueBasedPartialBidMatrixCalculationInputList",
    "WaterValueBasedPartialBidMatrixCalculationInputWriteList",
    "WaterValueBasedPartialBidMatrixCalculationInputApplyList",
    "WaterValueBasedPartialBidMatrixCalculationInputFields",
    "WaterValueBasedPartialBidMatrixCalculationInputTextFields",
]
