space: '{{powerops_models}}'
externalId: BidConfigurationShop
description: ''
name: BidConfigurationShop
filter:
  and:
  - hasData:
    - type: container
      space: '{{powerops_models}}'
      externalId: FunctionData
  - equals:
      property:
      - node
      - space
      value: '{{powerops_instance_space}}'
  - equals:
      property:
      - node
      - type
      value:
        externalId: BidConfigurationShop
        space: '{{powerops_type_space}}'
implements:
- space: '{{powerops_models}}'
  externalId: BidConfiguration
  version: '{{version}}'
  type: view
version: '{{version}}'
properties:
  method:
    container:
      space: '{{powerops_models}}'
      externalId: FunctionData
      type: container
    containerPropertyIdentifier: direct1
    name: method
    description: The bid method related to the bid configuration
    source:
      space: '{{powerops_models}}'
      externalId: BidMethodSHOPMultiScenario
      version: '{{version}}'
      type: view
  plantsShop:
    type:
      space: '{{powerops_type_space}}'
      externalId: BidConfiguration.plantsShop
    source:
      space: '{{powerops_models}}'
      externalId: PlantShop
      version: '{{version}}'
      type: view
    direction: outwards
    name: plants
    description: The plants modelled in the shop runs
    connectionType: multi_edge_connection
  watercoursesShop:
    type:
      space: '{{powerops_type_space}}'
      externalId: BidConfiguration.watercoursesShop
    source:
      space: '{{powerops_models}}'
      externalId: WatercourseShop
      version: '{{version}}'
      type: view
    direction: outwards
    name: watercourses
    description: The watercourses modelled in the shop runs
    connectionType: multi_edge_connection
