externalId: all_PowerOps
space: "{{powerops_models}}"
version: "{{version}}"
name: all_PowerOps
views:
  - externalId: SHOPResult
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidRow
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: MarketConfiguration
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Alert
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ModelTemplate
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Mapping
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidConfiguration
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialBidConfiguration
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopBasedPartialBidConfiguration
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: WaterValueBasedPartialBidConfiguration
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: SHOPTriggerInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: WaterValueBasedPartialBidMatrixCalculationInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PreprocessorInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: FunctionInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TotalBidMatrixCalculationInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TaskDispatcherInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopPartialBidMatrixCalculationInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Scenario
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ScenarioSet
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PreprocessorOutput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialBidMatrixCalculationInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialBidMatrixCalculationOutput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: SHOPTriggerOutput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: FunctionOutput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TaskDispatcherOutput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TotalBidMatrixCalculationOutput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidDocument
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidDocumentDayAhead
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidDocumentAFRR
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PowerAsset
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Generator
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TurbineEfficiencyCurve
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Plant
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceArea
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: GeneratorEfficiencyCurve
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceAreaAFRR
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidMatrix
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - space: "{{powerops_models}}"
    externalId: ShopObjectiveValue
    version: "{{version}}"
    type: view
  - externalId: TaskDispatcherBenchmarkingInput
    space: "{{powerops_models}}"
    version: "{{version}}"
    type: view
  - externalId: TaskDispatcherBenchmarkingOutput
    space: "{{powerops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BenchmarkingCollectorInput
    space: "{{powerops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BenchmarkingCollectorOutput
    space: "{{powerops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BidDocumentDayAheadSimple
    space: "{{powerops_models}}"
    version: "{{version}}"
    type: view
  - externalId: Case
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Commands
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceProduction
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: SHOPTimeSeries
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - space: "{{powerops_models}}"
    externalId: ShopFile
    version: "{{version}}"
    type: view
