externalId: compute_DayAheadBenchmarking
space: "{{power_ops_models}}"
version: "1"
name: DayAheadBenchmarking
description: "The process of benchmarking day-ahead bids"
views:
  - externalId: DayAheadBenchmarkingConfiguration
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopModelToAssets
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  #- externalId: TimeSeriesWithLabel
  #  space: "{{power_ops_models}}"
  #  version: "{{version}}"
  #  type: view
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingTaskDispatcherInput # PrepareDayAheadBenchmarkingShopRunsInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingTaskDispatcherOutput # PrepareDayAheadBenchmarkingShopRunsOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingShopRunInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingResult # DayAheadBenchmarkingShopRunOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadProductionObligationForBenchmarking
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BidSource
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BenchmarkingCollectorOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BenchmarkingCollectorInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: BidMatrix
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: Alert
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopScenario
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: FunctionInput
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: FunctionOutput
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: PriceArea
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopModel
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopCommands
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopAttributeMapping
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: PowerAsset
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: PartialBidConfiguration
    version: "{{version}}"
    type: view
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopFile
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopCase
    space: "sp_power_ops_models"
    type: view
    version: "1"
