externalId: compute_DayAheadBenchmarking
space: "{{power_ops_models}}"
version: "1"
name: DayAheadBenchmarking
description: "The process of benchmarking day-ahead bids"
views:
  - externalId: DayAheadBenchmarkingConfiguration
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopModelToAssets
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  #- externalId: TimeSeriesWithLabel
  #  space: "{{power_ops_models}}"
  #  version: "{{version}}"
  #  type: view
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopModel
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: PowerAsset
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: TaskDispatcherBenchmarkingInput  # PrepareDayAheadBenchmarkingShopRunsInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: TaskDispatcherBenchmarkingOutput  # PrepareDayAheadBenchmarkingShopRunsOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingShopRunInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopScenario
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingResult  # DayAheadBenchmarkingShopRunOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopObjectiveValue
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
