externalId: compute_DayAheadBenchmarking
space: "{{power_ops_models}}"
version: "1"
name: DayAheadBenchmarking
description: "The process of benchmarking day-ahead bids"
views:
  - externalId: TaskDispatcherBenchmarkingInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: TaskDispatcherBenchmarkingOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BenchmarkingCollectorInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BenchmarkingCollectorOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BidDocumentDayAheadSimple
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: BidMatrix
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: Alert
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopScenario
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopObjectiveValue
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: FunctionInput
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: FunctionOutput
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: PriceArea
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopModel
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopCommands
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopAttributeMapping
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: PowerAsset
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: PartialBidConfiguration
    version: "{{version}}"
    type: view
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopFile
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
