externalId: compute_TotalBidCalculation
space: '{{powerops_models}}'
version: '1'
name: TotalBidCalculation
description: 'The process of going from PartialBidMatrix to TotalBidMatrix'
views:
- externalId: BidMatrixRaw
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: BidMatrix
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: MultiScenarioMatrix
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: PartialPostProcessingInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: PartialPostProcessingOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: TotalBidMatrixCalculationInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: TotalBidMatrixCalculationOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: BidDocumentDayAhead
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: PriceArea
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: BidMethodDayAhead
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: BidMethodWaterValue
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: BidMethodSHOPMultiScenario
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: PriceScenario
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Alert
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: SHOPResult
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: MarketConfiguration
  space: "{{powerops_models}}"
  type: view
  version: "{{version}}"
- externalId: Scenario
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: ModelTemplate
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Mapping
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: WatercourseShop
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
