externalId: compute_TotalBidCalculation
space: "{{powerops_models}}"
version: "1"
name: TotalBidCalculation
description: "The process of going from PartialBidMatrix to TotalBidMatrix"
views:
  - externalId: BidMatrix
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialPostProcessingInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialPostProcessingOutput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TotalBidMatrixCalculationInput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TotalBidMatrixCalculationOutput
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidDocumentDayAhead
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceArea
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Alert
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: SHOPResult
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: SHOPResultPriceProd
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: MarketConfiguration
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Scenario
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ModelTemplate
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Mapping
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: WatercourseShop
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceProdCase
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Case
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: SHOPTimeSeries
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Commands
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - space: "{{powerops_models}}"
    externalId: FunctionInput
    version: "{{version}}"
    type: view
  - space: "{{powerops_models}}"
    externalId: FunctionOutput
    version: "{{version}}"
    type: view
  - space: "{{powerops_models}}"
    externalId: BidDocument
    version: "{{version}}"
    type: view
  - space: "{{powerops_models}}"
    externalId: PowerAsset
    version: "{{version}}"
    type: view
