externalId: compute_DayAheadBenchmarking
space: "{{power_ops_models}}"
version: "1"
name: DayAheadBenchmarking
description: "The process of benchmarking day-ahead bids"
views:
  - externalId: DayAheadBenchmarkingConfiguration
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopModelToAssets
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingTaskDispatcherInput # PrepareDayAheadBenchmarkingShopRunsInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingTaskDispatcherOutput # PrepareDayAheadBenchmarkingShopRunsOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingShopRunInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadBenchmarkingResult # DayAheadBenchmarkingShopRunOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: DayAheadProductionObligationForBenchmarking
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BidSource
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: MarketConfiguration
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BenchmarkingCollectorOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BenchmarkingCollectorInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: BidMatrix
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: Alert
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopScenario
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: FunctionInput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: FunctionOutput
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: PriceArea
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopModel
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopCommands
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopAttributeMapping
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: PowerAsset
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: PartialBidConfiguration
    space: "{{power_ops_models}}"
    version: "{{version}}"
    type: view
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models}}"
    type: view
  - externalId: ShopFile
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopCase
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopResult
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: DateSpecification
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopTimeSeries
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopTriggerInput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
