externalId: compute_WaterValueBasedDayAheadBid
space: '{{powerops_models}}'
version: '1'
name: WaterValueBasedDayAheadBidProcess
description: 'The process of going from BidConfig to a PartialBidMatrix'
views:
- externalId: TaskDispatcherWaterInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: TaskDispatcherWaterOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- space: '{{powerops_models}}'
  externalId: BidCalculationTask
  type: view
  version: '{{version}}'
- externalId: WaterPartialBidCalculationInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: WaterPartialBidCalculationOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- space: '{{powerops_models}}'
  externalId: BidMatrixRaw
  type: view
  version: '{{version}}'
- externalId: BidMethodWaterValue
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Plant
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Watercourse
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Alert
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: BidConfigurationWater
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: PriceScenario
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: PriceArea
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: MarketConfiguration
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Reservoir
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Generator
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: GeneratorEfficiencyCurve
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: TurbineEfficiencyCurve
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
