externalId: config_DayAheadConfiguration
space: "{{powerops_models}}"
version: "1"
name: DayAheadConfiguration
description: "Settings for the day ahead bid process"
views:
  - externalId: BidConfiguration
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidConfigurationShop
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidConfigurationWater
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: MarketConfiguration
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceScenario
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Watercourse
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: WatercourseShop
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Plant
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PlantShop
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Generator
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Reservoir
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TurbineEfficiencyCurve
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: GeneratorEfficiencyCurve
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidMethodDayAhead
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidMethodWaterValue
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidMethodSHOPMultiScenario
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceArea
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidMethod
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
