externalId: frontend_Asset
space: "{{powerops_models}}"
version: "1"
name: PowerAsset
description: "Describes the power operations asset model"
views:
  - externalId: PriceArea
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PowerAsset
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Plant
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Generator
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TurbineEfficiencyCurve
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: GeneratorEfficiencyCurve
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
