externalId: frontend_Asset
space: "{{power_ops_models}}"
version: "1"
name: PowerAsset
description: "Describes the power operations asset model"
views:
  - externalId: PriceArea
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceAreaAFRR
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceAreaInformation
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: MarketConfiguration
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialBidConfiguration
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PowerAsset
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Plant
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PlantWaterValueBased
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PlantInformation
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Watercourse
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Generator
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TurbineEfficiencyCurve
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: GeneratorEfficiencyCurve
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
