externalId: frontend_Asset
space: '{{powerops_models}}'
version: '1'
name: PowerAsset
description: 'Describes the power operations asset model'
views:
- externalId: PriceAreaAsset
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Watercourse
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Plant
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Generator
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Reservoir
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: TurbineEfficiencyCurve
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: GeneratorEfficiencyCurve
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: BidMethodDayAhead
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: PriceScenario
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
