externalId: frontend_DayAheadBid
space: "{{power_ops_models}}"
version: "1"
name: "DayAheadBid"
description: "Stores results of Day Ahead bid calculations."
views:
  - externalId: BidDocumentDayAhead
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidDocument
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidMatrix
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceArea
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Alert
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopScenario
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopModel
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopAttributeMapping
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceProduction
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopCommands
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopCase
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PowerAsset
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidConfiguration
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialBidConfiguration
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopResult
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: MarketConfiguration
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopTimeSeries
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
