externalId: product_CogShop
space: "{{powerops_models}}"
version: "1"
name: CogShop
description: CogShop data model
views:
  - externalId: ShopCase
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Scenario
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopCommands
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopAttributeMapping
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopModel
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PowerAsset
    space: "{{powerops_models}}"
    type: view
    version: "{{version}}"
