space: '{{powerops_models}}'
externalId: BidConfigurationAFRR
description: ''
name: BidConfigurationAFRR
version: '{{version}}'
properties:
  method:
    container:
      space: '{{powerops_models}}'
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: method
    name: method
    description: The bid method related to the bid configuration
    source:
      space: '{{powerops_models}}'
      externalId: BidMethodAFRR
      version: '{{version}}'
      type: view
  marketConfiguration:
    container:
      space: '{{powerops_models}}'
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: marketConfiguration
    name: marketConfiguration
    source:
      space: '{{powerops_models}}'
      externalId: MarketConfiguration
      version: '{{version}}'
      type: view
  priceArea:
    container:
      space: '{{powerops_models}}'
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: priceArea
    name: priceArea
    source:
      space: '{{powerops_models}}'
      externalId: PriceAreaAFRR
      version: '{{version}}'
      type: view
  plants:
    type:
      space: '{{powerops_type_space}}'
      externalId: BidConfiguration.plants
    source:
      space: '{{powerops_models}}'
      externalId: Plant
      version: '{{version}}'
      type: view
    direction: outwards
    name: plants
    description: The plants
    connectionType: multiEdgeConnection
  watercourses:
    type:
      space: '{{powerops_type_space}}'
      externalId: BidConfiguration.watercourses
    source:
      space: '{{powerops_models}}'
      externalId: Watercourse
      version: '{{version}}'
      type: view
    direction: outwards
    name: watercourses
    description: The watercourses
    connectionType: multiEdgeConnection
