space: '{{powerops_models}}'
externalId: BidConfigurationDayAhead
description: ''
name: BidConfigurationDayAhead
version: '{{version}}'
properties:
  method:
    container:
      space: '{{powerops_models}}'
      externalId: FunctionData
      type: container
    containerPropertyIdentifier: direct1
    name: method
    description: The bid method related to the bid configuration
    source:
      space: '{{powerops_models}}'
      externalId: BidMethodDayAhead
      version: '{{version}}'
      type: view
  marketConfiguration:
    container:
      space: '{{powerops_models}}'
      externalId: FunctionData
      type: container
    containerPropertyIdentifier: direct2
    name: marketConfiguration
    description: The bid method related to the bid configuration
    source:
      space: '{{powerops_models}}'
      externalId: MarketConfiguration
      version: '{{version}}'
      type: view
  priceArea:
    container:
      space: '{{powerops_models}}'
      externalId: BidDocument
      type: container
    containerPropertyIdentifier: priceArea
    name: priceArea
    description: The price area related to the bid configuration
    source:
      space: '{{powerops_models}}'
      externalId: PriceAreaDayAhead
      version: '{{version}}'
      type: view
  plants:
    type:
      space: '{{powerops_type_space}}'
      externalId: BidConfiguration.plants
    source:
      space: '{{powerops_models}}'
      externalId: Plant
      version: '{{version}}'
      type: view
    direction: outwards
    name: plants
    description: The plants
    connectionType: multiEdgeConnection
  watercourses:
    type:
      space: '{{powerops_type_space}}'
      externalId: BidConfiguration.watercourses
    source:
      space: '{{powerops_models}}'
      externalId: Watercourse
      version: '{{version}}'
      type: view
    direction: outwards
    name: watercourses
    description: The watercourses
    connectionType: multiEdgeConnection
