space: '{{powerops_models}}'
externalId: BidConfiguration
name: BidConfiguration
usedFor: node
properties:
  method:
    type:
      type: direct # points to BidMethod container
    nullable: false
    autoIncrement: false
    name: method
  marketConfiguration:
    type:
      type: direct
      list: false
    nullable: false
    autoIncrement: false
    name: marketConfiguration
  priceArea:
    type:
      type: direct
      list: false
    nullable: false
    autoIncrement: false
    name: priceArea
indexes:
  methodIndex:
    properties:
    - method
    indexType: btree
    cursorable: false
  priceAreaIndex:
    properties:
    - priceArea
    indexType: btree
    cursorable: false
