space: "{{power_ops_models}}"
externalId: ShopBasedPartialBidConfiguration
name: ShopBasedPartialBidConfiguration
description: TODO
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models}}"
          externalId: PartialBidConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          externalId: ShopBasedPartialBidConfiguration
          space: "{{power_ops_type_space}}"
implements:
  - space: "{{power_ops_models}}"
    externalId: PartialBidConfiguration
    version: "{{version}}"
    type: view
version: "{{version}}"
properties:
  scenarioSet:
    container:
      space: "{{power_ops_models}}"
      externalId: ShopPartialBidConfiguration
      type: container
    containerPropertyIdentifier: scenarioSet
    name: scenarioSet
    source:
      space: "{{power_ops_models}}"
      externalId: ShopScenarioSet
      version: "{{version}}"
      type: view
