[cdf]
default_env = "dev"

[feature_flags]
require-kind = true

[modules]
# This is the version of the modules. It should not be changed manually.
# It will be updated by the 'cdf module upgrade' command.
version = "0.3.4"


[plugins]
run = true
pull = false
dump = false
