environment:
  project: oe-prod
  type: prod
  selected:
    - modules/power_model

variables:
  modules:
    power_ops_type_space: "power_ops_types"
    power_ops_instance_space: "power_ops_instances"
    power_ops_models: "power_ops_core"
    version: "1"
