environment:
  project: power-ops-sandbox
  # type is set to staging since this field is only used for raising error if project defined here
  # doesn't match the environment variables (valid options are dev, staging, prod)
  validation-type: staging
  selected:
    - modules/power_model
    - modules/resync
    - modules/power_ops_template
    - modules/shop_result_explorer

variables:
  modules:
    # variables required for BOTH power_model and power_ops_template
    power_ops_type_space: "power_ops_types"
    power_ops_instance_space: "power_ops_instances"
    power_ops_models_space: "power_ops_core"
    power_ops_data_model_version: "1"
    # variables required for ONLY power_ops_template
    wf_day_ahead_market: "DAY_AHEAD"
    wf_day_ahead_bid_process_xid: "DayAheadBidProcess"
    wf_day_ahead_bid_process_version: "latest"
    wf_day_ahead_bid_process_cron: "30 7 * * *" # translates to 7:30 UTC / 9:30 CEST
    wf_day_ahead_bid_process_cron_15_min: "30 6 * * *" # translates to 6:30 UTC / 8:30 CEST
    wf_trigger_client_id: "d985b4fe-275e-4df3-9e49-b6b18a77778a"
    wf_trigger_client_secret: ${WF_TRIGGER_SECRET}
    # variables used for optional group set up in power_ops_template
    read_only_group_source_id: 497b3c43-950c-48de-9e41-87246f2ca510
    read_write_group_source_id: 3ac1480d-2b64-43e9-824b-7553940b7d41
    admin_read_write_group_source_id: 01986145-61d1-4cef-b7c9-f31261a429a0
