from __future__ import annotations

from cognite.powerops.bootstrap.config_classes.marked_configuration._core import PriceScenario, PriceScenarioID
from cognite.powerops.bootstrap.config_classes.marked_configuration.benchmarking import BenchmarkingConfig
