space: "{{power_ops_models}}"
externalId: PartialBidConfiguration
name: PartialBidConfiguration
description: A partial bid configuration
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models}}"
          externalId: PartialBidConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
version: "{{version}}"
properties:
  name:
    container:
      space: "{{power_ops_models}}"
      externalId: PartialBidConfiguration
      type: container
    containerPropertyIdentifier: name
    name: name
    description: Name for the PartialBidConfiguration
  method:
    container:
      space: "{{power_ops_models}}"
      externalId: PartialBidConfiguration
      type: container
    containerPropertyIdentifier: method
    name: method
    description: Name of the method used for the bid calculation
  powerAsset:
    container:
      space: "{{power_ops_models}}"
      externalId: PartialBidConfiguration
      type: container
    containerPropertyIdentifier: powerAsset
    name: powerAsset
    description: TODO description
    source:
      space: "{{power_ops_models}}"
      externalId: PowerAsset
      version: "{{version}}"
      type: view
  addSteps:
    container:
      space: "{{power_ops_models}}"
      externalId: PartialBidConfiguration
      type: container
    containerPropertyIdentifier: addSteps
    name: addSteps
    description: TODO definition
