space: "{{powerops_models}}"
externalId: BidConfiguration
name: BidConfiguration
description: ""
filter:
  and:
    - hasData:
        - type: container
          space: "{{powerops_models}}"
          externalId: BidConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{powerops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          space: "{{powerops_type_space}}"
          externalId: BidConfiguration
implements: []
version: "{{version}}"
properties:
  name:
    container:
      space: "{{powerops_models}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: name
    name: name
    description: The name of the bid configuration
  marketConfiguration:
    container:
      space: "{{powerops_models}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: marketConfiguration
    name: marketConfiguration
    description: The market configuration related to the bid configuration
    source:
      space: "{{powerops_models}}"
      externalId: MarketConfiguration
      version: "{{version}}"
      type: view
  priceArea:
    container:
      space: "{{powerops_models}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: priceArea
    name: priceArea
    description: The price area related to the bid calculation task
    source:
      space: "{{powerops_models}}"
      externalId: PriceArea
      version: "{{version}}"
      type: view
  partials:
    type:
      space: "{{powerops_type_space}}"
      externalId: BidConfiguration.partials
    source:
      space: "{{powerops_models}}"
      externalId: PartialBidConfiguration
      version: "{{version}}"
      type: view
    direction: outwards
    name: partials
    description: Configuration of the partial bids that make up the total bid
    connectionType: multi_edge_connection
