space: "{{powerops_models}}"
externalId: ShopBasedPartialBidConfiguration
name: ShopBasedPartialBidConfiguration
description: A description of the ShopBasedPartialBidConfiguration
filter:
  and:
    - hasData:
        - type: container
          space: "{{powerops_models}}"
          externalId: PartialBidConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{powerops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          externalId: ShopBasedPartialBidConfiguration
          space: "{{powerops_type_space}}"
implements:
  - space: "{{powerops_models}}"
    externalId: PartialBidConfiguration
    version: "{{version}}"
    type: view
version: "{{version}}"
properties:
  method:
    container:
      space: "{{powerops_models}}"
      externalId: PartialBidConfiguration
      type: container
    containerPropertyIdentifier: method
    name: method
    description: The bid method related to the bid configuration
    source:
      space: "{{powerops_models}}"
      externalId: BidMethodSHOPMultiScenario #TODO: update to right bid method
      version: "{{version}}"
      type: view
  asset:
    container:
      space: "{{powerops_models}}"
      externalId: PartialBidConfiguration
      type: container
    containerPropertyIdentifier: asset
    name: asset
    description: TODO description
    source:
      space: "{{powerops_models}}"
      externalId: PowerAsset # TODO: update to right asset
      version: "{{version}}"
      type: view
  cutOffPrice:
    container:
      space: "{{powerops_models}}"
      externalId: PartialShopBased
      type: container
    containerPropertyIdentifier: cutOffPrice
    name: cutOffPrice
    description: TODO definition
  shopStartSpecification:
    container:
      space: "{{powerops_models}}"
      externalId: PartialShopBased
      type: container
    containerPropertyIdentifier: shopStartSpecification
    name: shopStartSpecification
    description: TODO definition
  shopEndSpecification:
    container:
      space: "{{powerops_models}}"
      externalId: PartialShopBased
      type: container
    containerPropertyIdentifier: shopEndSpecification
    name: shopEndSpecification
    description: TODO definition
  shopBidDateSpecification:
    container:
      space: "{{powerops_models}}"
      externalId: PartialShopBased
      type: container
    containerPropertyIdentifier: shopBidDateSpecification
    name: shopBidDateSpecification
    description: TODO definition
  shopScenarios:
    type:
      space: "{{powerops_type_space}}"
      externalId: ShopBasedPartialBidConfiguration.scenarios
    source:
      space: "{{powerops_models}}"
      externalId: Scenario
      version: "{{version}}"
      type: view
    direction: outwards
    name: shopScenarios
    description: Configuration of the partial bids that make up the total bid configuration
    connectionType: multi_edge_connection
