space: "{{power_ops_models_space}}"
externalId: DataSetConfiguration
name: DataSetConfiguration
description: Data Set configuration
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models_space}}"
          externalId: DataSetConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          externalId: DataSetConfiguration
          space: "{{power_ops_type_space}}"

version: "{{power_ops_data_model_version}}"
properties:
  readDataSet:
    container:
      space: "{{power_ops_models_space}}"
      externalId: DataSetConfiguration
      type: container
    containerPropertyIdentifier: readDataSet
    name: readDataSet
    description: The data set to read data from into the solution
  writeDataSet:
    container:
      space: "{{power_ops_models_space}}"
      externalId: DataSetConfiguration
      type: container
    containerPropertyIdentifier: writeDataSet
    name: writeDataSet
    description: The data set to write solution data to
  monitorDataSet:
    container:
      space: "{{power_ops_models_space}}"
      externalId: DataSetConfiguration
      type: container
    containerPropertyIdentifier: monitorDataSet
    name: monitorDataSet
    description: The data set to write monitoring data to, like logs from the solution
  processDataset:
    container:
      space: "{{power_ops_models_space}}"
      externalId: DataSetConfiguration
      type: container
    containerPropertyIdentifier: processDataset
    name: processDataset
    description: The data set to process data from into the solution
