externalId: compute_WaterValueBasedDayAheadBid
space: '{{powerops_models}}'
version: '1'
name: WaterValueBasedDayAheadBidProcess
description: 'The process of going from BidConfig to a PartialBidMatrix'
views:
- externalId: FunctionInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: FunctionOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: TaskDispatcherWaterInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: TaskDispatcherWaterOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- space: '{{powerops_models}}'
  externalId: BidCalculationTask
  type: view
  version: '{{version}}'
- externalId: WaterPartialBidCalculationInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: WaterPartialBidCalculationOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- space: '{{powerops_models}}'
  externalId: BidMatrixRaw
  type: view
  version: '{{version}}'
- externalId: BidMethodDayAhead
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Alert
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
