externalId: compute_WaterValueBasedDayAheadBid
space: '{{powerops_models}}'
version: '1'
name: WaterValueBasedDayAheadBidProcess
description: 'The process of going from BidConfig to a PartialBidMatrix'
views:
- externalId: TaskDispatcherInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: TaskDispatcherOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- space: '{{powerops_models}}'
  externalId: BidCalculationTask
  type: view
  version: '{{version}}'
- externalId: BidCalculationInput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: BidCalculationOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- space: '{{powerops_models}}'
  externalId: BidMatrixRaw
  type: view
  version: '{{version}}'
- externalId: BidMethodWaterValueBased
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
- externalId: Alert
  space: '{{powerops_models}}'
  type: view
  version: '{{version}}'
