externalId: WaterValueBasedDayAheadBidProcess
space: '{{'power-ops-day-ahead-backend'}}'
version: '1'
name: WaterValueBasedDayAheadBidProcess
description: 'The process of going from BidConfig to a PartialBidMatrix'
views:
-

- space: '{{dayahead_model_space}}'
  externalId: BidMatrixRaw
  type: view
  version: '{{dayaheadbid_BidMethod_version}}'
- externalId: BidMethodWaterValueBased
  space: '{{dayahead_model_space}}'
  type: view
  version: '{{dayaheadbid_BidMethod_version}}'
- externalId: Alert
  space: '{{shared_model_space}}'
  type: view
  version: '{{base_Alert_version}}'
