externalId: WaterValueBasedDayAheadBidProcess
space: '{{'power-ops-day-ahead-backend'}}'
version: '1'
name: WaterValueBasedDayAheadBidProcess
description: 'The process of going from BidConfig to a PartialBidMatrix'
views:
- space: '{{day_ahead_backend_space}}'
  externalId: FunctionInput
  type: view
  version: '{{}}'
- externalId: FunctionOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{}}'
- externalId: TaskDispatcherInput
  space: '{{powerops_models}}'
  type: view
  version: '{{}}'
- space: '{{powerops_models}}'
  externalId: BidCalculationTask
  type: view
  version: '{{}}'
- externalId: BidCalculationInput
  space: '{{powerops_models}}'
  type: view
  version: '{{}}'
- externalId: BidCalculationOutput
  space: '{{powerops_models}}'
  type: view
  version: '{{}}'
# Done
- space: '{{powerops_models}}'
  externalId: BidMatrixRaw
  type: view
  version: '{{dayaheadbid_BidMethod_version}}'
- externalId: BidMethodWaterValueBased
  space: '{{powerops_models}}'
  type: view
  version: '{{dayaheadbid_BidMethod_version}}'
- externalId: Alert
  space: '{{powerops_models}}'
  type: view
  version: '{{base_Alert_version}}'
