- externalId: shop_based_partial_bid_configuration_15_min_sola_1
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: price independent
      name: 15 min Sola 1
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_15_min_stavanger_1_scenario
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_15_min_sola_2
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: multi scenario 2
      name: 15 min Sola 2
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_15_min_stavanger_2_scenarios
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_15_min_sola_20
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: multi scenario 20
      name: 15 min Sola 20
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_15_min_stavanger_20_scenarios
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_15_min_sola_3
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: multi scenario 3
      name: 15 min Sola 3
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_15_min_stavanger_3_scenarios
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_15_min_sola_3_step
  instanceType: node
  sources:
  - properties:
      addSteps: true
      method: multi scenario 3
      name: 15 min Sola 3 step
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_15_min_stavanger_3_scenarios
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_sola_1
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: price independent
      name: Sola 1
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_stavanger_1_scenario
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_sola_2
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: multi scenario 2
      name: Sola 2
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_stavanger_2_scenarios
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_sola_20
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: multi scenario 20
      name: Sola 20
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_stavanger_20_scenarios
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_sola_3
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: multi scenario 3
      name: Sola 3
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_stavanger_3_scenarios
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
- externalId: shop_based_partial_bid_configuration_sola_3_step
  instanceType: node
  sources:
  - properties:
      addSteps: true
      method: multi scenario 3
      name: Sola 3 step
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
      scenarioSet:
        externalId: shop_scenario_set_stavanger_3_scenarios
        space: power_ops_instances
    source:
      externalId: ShopBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: power_ops_types
