- externalId: water_value_based_partial_bid_configuration_plant_sola
  instanceType: node
  sources:
  - properties:
      addSteps: false
      method: Water Value Based Bid Generation (WVBBG)
      name: Plant Sola
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
    source:
      externalId: WaterValueBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: WaterValueBasedPartialBidConfiguration
    space: power_ops_types
- externalId: water_value_based_partial_bid_configuration_plant_sola_step
  instanceType: node
  sources:
  - properties:
      addSteps: true
      method: Water Value Based Bid Generation (WVBBG)
      name: Plant Sola Step
      powerAsset:
        externalId: plant_information_sola
        space: power_ops_instances
    source:
      externalId: WaterValueBasedPartialBidConfiguration
      space: power_ops_core
      type: view
      version: '1'
  space: power_ops_instances
  type:
    externalId: WaterValueBasedPartialBidConfiguration
    space: power_ops_types
