- externalId: shop_based_partial_bid_configuration_sola_1
  sources:
    - properties:
        addSteps: false
        method: price independent
        name: Sola 1
        powerAsset:
          externalId: plant_information_sola
          space: '{{power_ops_instance_space}}'
        scenarioSet:
          externalId: shop_scenario_set_stavanger_1_scenario
          space: '{{power_ops_instance_space}}'
      source:
        externalId: ShopBasedPartialBidConfiguration
        space: '{{power_ops_models_space}}'
        type: view
        version: '{{power_ops_data_model_version}}'
  space: '{{power_ops_instance_space}}'
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: '{{power_ops_type_space}}'
- externalId: shop_based_partial_bid_configuration_sola_2
  sources:
    - properties:
        addSteps: false
        method: multi scenario 2
        name: Sola 2
        powerAsset:
          externalId: plant_information_sola
          space: '{{power_ops_instance_space}}'
        scenarioSet:
          externalId: shop_scenario_set_stavanger_2_scenarios
          space: '{{power_ops_instance_space}}'
      source:
        externalId: ShopBasedPartialBidConfiguration
        space: '{{power_ops_models_space}}'
        type: view
        version: '{{power_ops_data_model_version}}'
  space: '{{power_ops_instance_space}}'
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: '{{power_ops_type_space}}'
- externalId: shop_based_partial_bid_configuration_sola_3_step
  sources:
    - properties:
        addSteps: true
        method: multi scenario 3
        name: Sola 3 step
        powerAsset:
          externalId: plant_information_sola
          space: '{{power_ops_instance_space}}'
        scenarioSet:
          externalId: shop_scenario_set_stavanger_3_scenarios
          space: '{{power_ops_instance_space}}'
      source:
        externalId: ShopBasedPartialBidConfiguration
        space: '{{power_ops_models_space}}'
        type: view
        version: '{{power_ops_data_model_version}}'
  space: '{{power_ops_instance_space}}'
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: '{{power_ops_type_space}}'
- externalId: shop_based_partial_bid_configuration_sola_3
  sources:
    - properties:
        addSteps: false
        method: multi scenario 3
        name: Sola 3
        powerAsset:
          externalId: plant_information_sola
          space: '{{power_ops_instance_space}}'
        scenarioSet:
          externalId: shop_scenario_set_stavanger_3_scenarios
          space: '{{power_ops_instance_space}}'
      source:
        externalId: ShopBasedPartialBidConfiguration
        space: '{{power_ops_models_space}}'
        type: view
        version: '{{power_ops_data_model_version}}'
  space: '{{power_ops_instance_space}}'
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: '{{power_ops_type_space}}'
- externalId: shop_based_partial_bid_configuration_sola_20
  sources:
    - properties:
        addSteps: false
        method: multi scenario 20
        name: Sola 20
        powerAsset:
          externalId: plant_information_sola
          space: '{{power_ops_instance_space}}'
        scenarioSet:
          externalId: shop_scenario_set_stavanger_20_scenarios
          space: '{{power_ops_instance_space}}'
      source:
        externalId: ShopBasedPartialBidConfiguration
        space: '{{power_ops_models_space}}'
        type: view
        version: '{{power_ops_data_model_version}}'
  space: '{{power_ops_instance_space}}'
  type:
    externalId: ShopBasedPartialBidConfiguration
    space: '{{power_ops_type_space}}'
