# variables used for substitution in other files in this directory

model_space: 'power-ops-day-ahead-bids'
model_external_id: 'DayAheadBids'
model_version: '1'
model_name: 'DayAheadBids'

shared_model_space: 'power-ops-base-bids'

view_BidDocument_version: '1'
view_BidMethod_version: '1'
view_PriceArea_version: '1'
view_SHOPMultiScenario_version: '1'
view_WaterValueBased_version: '1'
view_BidTable_version: '1'
view_SHOPTable_version: '1'
view_ProductionPricePair_version: '1'

view_Alert_version: '1'
