externalId: '{{data_model}}'
name: '{{data_model}}'
space: '{{model_space}}'
version: '{{data_model_version}}'
views:
- externalId: Alert
  space: '{{model_space}}'
  type: view
  version: '{{view_Alert_version}}'

- externalId: BidMethod
  space: '{{model_space}}'
  type: view
  version: '{{view_Alert_version}}'
- externalId: WaterValueBased
  space: '{{model_space}}'
  type: view
  version: '{{view_WaterValueBased_version}}'
- externalId: SHOP
  space: '{{model_space}}'
  type: view
  version: '{{view_SHOP_version}}'

- externalId: MarketPriceArea
  space: '{{model_space}}'
  type: view
  version: '{{view_MarketPriceArea_version}}'

- externalId: BidTable
  space: '{{model_space}}'
  type: view
  version: '{{view_BidTable_version}}'
- externalId: SHOPTable
  space: '{{model_space}}'
  type: view
  version: '{{view_SHOPTable_version}}'

- externalId: ProductionPricePair
  space: '{{model_space}}'
  type: view
  version: '{{view_ProductionPricePair_version}}'

- externalId: Bid
  space: '{{model_space}}'
  type: view
  version: '{{view_Bid_version}}'
