externalId: all_PowerOps
space: "{{power_ops_models_space}}"
version: "{{power_ops_data_model_version}}"
name: all_PowerOps
views:
  - externalId: ShopResult
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BidRow
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: MarketConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: Alert
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopModel
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopAttributeMapping
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopBasedPartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: WaterValueBasedPartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopTriggerInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: WaterValueBasedPartialBidMatrixCalculationInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopPreprocessorInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: FunctionInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: TotalBidMatrixCalculationInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: TaskDispatcherInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: MultiScenarioPartialBidMatrixCalculationInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopScenario
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopScenarioSet
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopPreprocessorOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PartialBidMatrixCalculationInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PartialBidMatrixCalculationOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopTriggerOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: FunctionOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: TaskDispatcherOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: TotalBidMatrixCalculationOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BidDocument
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BidDocumentDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BidDocumentAFRR
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PowerAsset
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: Generator
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: TurbineEfficiencyCurve
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: Watercourse
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: Plant
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PlantWaterValueBased
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PlantInformation
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PriceArea
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PriceAreaInformation
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: GeneratorEfficiencyCurve
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PriceAreaAFRR
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BidMatrix
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BenchmarkingTaskDispatcherInputDayAhead
    space: "{{power_ops_models_space}}"
    version: "{{power_ops_data_model_version}}"
    type: view
  - externalId: BenchmarkingTaskDispatcherOutputDayAhead
    space: "{{power_ops_models_space}}"
    version: "{{power_ops_data_model_version}}"
    type: view
  - externalId: BenchmarkingCalculationInput
    space: "{{power_ops_models_space}}"
    version: "{{power_ops_data_model_version}}"
    type: view
  - externalId: BenchmarkingCalculationOutput
    space: "{{power_ops_models_space}}"
    version: "{{power_ops_data_model_version}}"
    type: view
  - externalId: ShopCase
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopTimeResolution
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopCommands
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PriceProduction
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopTimeSeries
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - space: "{{power_ops_models_space}}"
    externalId: ShopFile
    version: "{{power_ops_data_model_version}}"
    type: view
  - externalId: BidMatrixInformation
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PartialBidMatrixInformation
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: PartialBidMatrixInformationWithScenarios
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopPenaltyReport
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BenchmarkingShopCase
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopModelWithAssets
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BenchmarkingProductionObligationDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BenchmarkingResultDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: BenchmarkingConfigurationDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: DateSpecification
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: DataSetConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
