externalId: all_DayAhead
space: "{{power_ops_models_space}}"
version: "1"
name: All DayAhead
description: "Settings for the day ahead bid process"
views:
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: MarketConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PriceArea
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopBasedPartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: WaterValueBasedPartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopScenario
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopScenarioSet
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopAttributeMapping
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopModel
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: Generator
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: TurbineEfficiencyCurve
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: GeneratorEfficiencyCurve
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopCommands
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: Plant
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PlantWaterValueBased
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: TaskDispatcherInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: TaskDispatcherOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopPreprocessorInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopPreprocessorOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopTriggerInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopTriggerOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PartialBidMatrixCalculationInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: MultiScenarioPartialBidMatrixCalculationInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PartialBidMatrixCalculationOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: BidMatrix
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopResult
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: Alert
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PriceProduction
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopTimeSeries
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - space: "{{power_ops_models_space}}"
    externalId: FunctionInput
    version: "{{power_ops_version}}"
    type: view
  - space: "{{power_ops_models_space}}"
    externalId: FunctionOutput
    version: "{{power_ops_version}}"
    type: view
  - externalId: WaterValueBasedPartialBidMatrixCalculationInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: TotalBidMatrixCalculationInput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: TotalBidMatrixCalculationOutput
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: BidDocumentDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopCase
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - space: "{{power_ops_models_space}}"
    externalId: BidDocument
    version: "{{power_ops_version}}"
    type: view
  - space: "{{power_ops_models_space}}"
    externalId: PowerAsset
    version: "{{power_ops_version}}"
    type: view
  - space: "{{power_ops_models_space}}"
    externalId: ShopFile
    version: "{{power_ops_version}}"
    type: view
  - space: "{{power_ops_models_space}}"
    externalId: BidMatrixInformation
    version: "{{power_ops_version}}"
    type: view
  - space: "{{power_ops_models_space}}"
    externalId: PartialBidMatrixInformation
    version: "{{power_ops_version}}"
    type: view
  - externalId: DateSpecification
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
