externalId: compute_ShopBasedDayAhead
space: "{{power_ops_models}}"
version: "1"
name: ShopBasedDayAheadBidProcess
description: "The process of going from BidConfig to a PartialBidMatrix"
views:
  - externalId: TaskDispatcherInput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: TaskDispatcherOutput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopPreprocessorInput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopPreprocessorOutput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopTriggerInput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopTriggerOutput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialBidMatrixCalculationInput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: MultiScenarioPartialBidMatrixCalculationInput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PartialBidMatrixCalculationOutput
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidMatrix
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: MarketConfiguration
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopScenario
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopScenarioSet
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopAttributeMapping
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopModel
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopResult
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopCase
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: Alert
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceArea
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: PriceProduction
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopTimeSeries
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopCommands
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - space: "{{power_ops_models}}"
    externalId: FunctionInput
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: FunctionOutput
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: PowerAsset
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: PartialBidConfiguration
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopBasedPartialBidConfiguration
    version: "{{version}}"
    type: view
  - space: "{{power_ops_models}}"
    externalId: ShopFile
    version: "{{version}}"
    type: view
  - externalId: DateSpecification
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models}}"
    type: view
    version: "{{version}}"
