externalId: config_DayAheadConfiguration
space: "{{power_ops_models_space}}"
version: "1"
name: DayAheadConfiguration
description: "Settings for the day ahead bid process"
views:
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: MarketConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PriceArea
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopBasedPartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: WaterValueBasedPartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopScenario
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopScenarioSet
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopAttributeMapping
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopModel
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: Generator
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: TurbineEfficiencyCurve
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: GeneratorEfficiencyCurve
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopCommands
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PowerAsset
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: Plant
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PlantInformation
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PlantWaterValueBased
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: DateSpecification
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopFile
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
