externalId: frontend_DayAheadBid
space: "{{power_ops_models_space}}"
version: "1"
name: "DayAheadBid"
description: "Stores results of Day Ahead bid calculations."
views:
  - externalId: BidDocumentDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: BidDocument
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PriceArea
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PriceAreaDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: Alert
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopScenario
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopModel
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopAttributeMapping
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PriceProduction
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopCommands
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopCase
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PowerAsset
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: BidConfigurationDayAhead
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PartialBidConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopResult
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: MarketConfiguration
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopTimeSeries
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopFile
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: BidMatrix
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: BidMatrixInformation
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PartialBidMatrixInformation
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: PartialBidMatrixInformationWithScenarios
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopPenaltyReport
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: DateSpecification
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_version}}"
