externalId: product_CogShop
space: "{{power_ops_models_space}}"
version: "1"
name: CogShop
description: CogShop data model
views:
  - externalId: ShopCase
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopScenario
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopCommands
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopAttributeMapping
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopModel
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopResult
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopTimeSeries
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: Alert
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopFile
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
  - externalId: ShopOutputTimeSeriesDefinition
    space: "{{power_ops_models_space}}"
    type: view
    version: "{{power_ops_data_model_version}}"
