space: "{{power_ops_models_space}}"
externalId: BidConfigurationDayAhead
name: BidConfigurationDayAhead
description: TODO
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models_space}}"
          externalId: BidConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          space: "{{power_ops_type_space}}"
          externalId: BidConfigurationDayAhead
implements: []
version: "{{version}}"
properties:
  name:
    container:
      space: "{{power_ops_models_space}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: name
    name: name
    description: The name of the bid configuration
  marketConfiguration:
    container:
      space: "{{power_ops_models_space}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: marketConfiguration
    name: marketConfiguration
    description: The market configuration related to the bid configuration
    source:
      space: "{{power_ops_models_space}}"
      externalId: MarketConfiguration
      version: "{{version}}"
      type: view
  priceArea:
    container:
      space: "{{power_ops_models_space}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: priceArea
    name: priceArea
    description: The price area related to the bid calculation task
    source:
      space: "{{power_ops_models_space}}"
      externalId: PriceAreaDayAhead
      version: "{{version}}"
      type: view
  bidDateSpecification:
    container:
      space: "{{power_ops_models_space}}"
      externalId: BidConfiguration
      type: container
    containerPropertyIdentifier: bidDateSpecification
    name: bidDateSpecification
    description: TODO description
    source:
      space: "{{power_ops_models_space}}"
      externalId: DateSpecification
      version: "{{version}}"
      type: view
  partials:
    type:
      space: "{{power_ops_type_space}}"
      externalId: BidConfiguration.partials
    source:
      space: "{{power_ops_models_space}}"
      externalId: PartialBidConfiguration
      version: "{{version}}"
      type: view
    direction: outwards
    name: partials
    description: Configuration of the partial bids that make up the total bid
    connectionType: multi_edge_connection
