space: "{{power_ops_models_space}}"
externalId: WaterValueBasedPartialBidConfiguration
name: WaterValueBasedPartialBidConfiguration
description: A description of the WaterValueBasedPartialBidConfiguration
filter:
  and:
    - hasData:
        - type: container
          space: "{{power_ops_models_space}}"
          externalId: PartialBidConfiguration
    - equals:
        property:
          - node
          - space
        value: "{{power_ops_instance_space}}"
    - equals:
        property:
          - node
          - type
        value:
          externalId: WaterValueBasedPartialBidConfiguration
          space: "{{power_ops_type_space}}"
implements:
  - space: "{{power_ops_models_space}}"
    externalId: PartialBidConfiguration
    version: "{{power_ops_data_model_version}}"
    type: view
version: "{{power_ops_data_model_version}}"
properties:
  powerAsset:
    container:
      space: "{{power_ops_models_space}}"
      externalId: PartialBidConfiguration
      type: container
    containerPropertyIdentifier: powerAsset
    name: powerAsset
    description: TODO description (has to be a Plant)
    source:
      space: "{{power_ops_models_space}}"
      externalId: PlantWaterValueBased
      version: "{{power_ops_data_model_version}}"
      type: view
