space: "{{powerops_models}}"
externalId: MarketConfiguration
name: MarketConfiguration
usedFor: node
properties:
  name:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: true
    autoIncrement: false
    name: name
  maxPrice:
    type:
      list: false
      type: float64
    nullable: false
    autoIncrement: false
    name: maxPrice
    description: The highest price allowed
  minPrice:
    type:
      list: false
      type: float64
    nullable: false
    autoIncrement: false
    name: minPrice
    description: The lowest price allowed
  timeZone:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: false
    autoIncrement: false
    name: timeZone
    description:
  priceUnit:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: false
    autoIncrement: false
    name: priceUnit
    description: Unit of measurement for the price ("EUR/MWh")
  priceSteps:
    type:
      list: false
      collation: ucs_basic
      type: int64
    nullable: false
    autoIncrement: false
    name: priceSteps
    description: The maximum number of price steps
  tickSize:
    type:
      list: false
      collation: ucs_basic
      type: float64
    nullable: false
    autoIncrement: false
    name: tickSize
    description: '"Granularity" of the price; tick size = 0.1 means that prices must be "rounded to nearest 0.1" (i. e. 66.43 is not allowed, but 66.4 is)'
  timeUnit:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: false
    autoIncrement: false
    name: timeUnit
    description: The time unit ("1h")
  tradeLot:
    type:
      list: false
      collation: ucs_basic
      type: float64
    nullable: false
    autoIncrement: false
    name: tradeLot
    description: '"Granularity" of the volumes; trade lot = 0.2 means that volumes must be "rounded to nearest 0.2" (i. e. 66.5 is not allowed, but 66.4 is)'
indexes:
  priceStepsIndex:
    properties:
      - priceSteps
    indexType: btree
    cursorable: false
