space: "{{powerops_models}}"
externalId: PartialBidConfiguration
name: PartialBidConfiguration
usedFor: node
properties:
  name:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: false
    autoIncrement: false
    name: name
  asset:
    type:
      type: direct
      list: false
    nullable: false
    autoIncrement: false
    name: asset
  method:
    type:
      type: direct
      list: false
    nullable: false
    autoIncrement: false
    name: method
  addSteps:
    type:
      type: boolean
      list: false
    nullable: false
    autoIncrement: false
    name: addSteps
indexes:
  assetIndex:
    properties:
      - asset
    indexType: btree
    cursorable: false
