space: "{{power_ops_models}}"
externalId: ProductionObligationForBenchmarkingDayAhead
name: ProductionObligationForBenchmarkingDayAhead
usedFor: node
properties:
  timeseries:
    type:
      list: false
      type: timeseries
    nullable: true
    autoIncrement: false
    name: timeseries
    description: The time series of the day ahead production obligation for benchmarking
  name:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: true
    autoIncrement: false
    name: name
    description: The name of the day ahead production obligation for benchmarking
