space: "{{power_ops_models_space}}"
externalId: DataSetConfiguration
name: DataSetConfiguration
usedFor: node
properties:
  name:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: false
    autoIncrement: false
    name: name
  readDataSet:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: false
    autoIncrement: false
    name: readDataSet
  writeDataSet:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: false
    autoIncrement: false
    name: writeDataSet
  monitorDataSet:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: true
    autoIncrement: false
    name: monitorDataSet
  processDataSet:
    type:
      list: false
      collation: ucs_basic
      type: text
    nullable: true
    autoIncrement: false
    name: processDataSet
