name: release

on:
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.9"

jobs:
  test_and_release:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install core dependencies
        run: |
          python3 -m pip install --upgrade pip poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Test
        env:
          SETTINGS__COGNITE__CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SETTINGS__COGNITE__CLIENT_ID: ${{ vars.CLIENT_ID }}
          SETTINGS__COGNITE__PROJECT: ${{ vars.PROJECT }}
          SETTINGS__COGNITE__CDF_CLUSTER: ${{ vars.CLUSTER }}
          SETTINGS__COGNITE__TENANT_ID: ${{ vars.TENANT_ID }}
          SETTINGS__COGNITE__LOGIN_FLOW: "client_credentials"
        run: pytest

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

      - name: Build package
        run: poetry build

      - name: Release to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        shell: bash
        run: twine upload --skip-existing --verbose dist/*
