name: Resync Apply "v1"

on:
  push:
    branches:
      - main
    paths:
      - "cognite/powerops/resync/v1/**.py"
      - "cognite/powerops/cli.py"
      - "tests/data/demo/v1/**.yaml"
      - "tests/data/demo/v1/**.yml"

jobs:
  resync-plan:
    name: Resync Apply "v1" to CDF project ${{ vars.PROJECT }}

    environment:
      name: dev

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry==1.*
          poetry config virtualenvs.create false
          poetry install

      - name: Run resync plan
        env:
          SETTINGS__COGNITE__CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SETTINGS__COGNITE__CLIENT_ID: ${{ vars.CLIENT_ID }}
          SETTINGS__COGNITE__PROJECT: ${{ vars.PROJECT }}
          SETTINGS__COGNITE__CDF_CLUSTER: ${{ vars.CLUSTER }}
          SETTINGS__COGNITE__TENANT_ID: ${{ vars.TENANT_ID }}
        run: |
          echo Running resync apply in CDF environment $SETTINGS__COGNITE__PROJECT
          powerops apply_v1 tests/data/demo/v1/resync_configuration.yaml
