name: Resync Plan "v1"

on:
  pull_request:
    branches:
      - main
    paths:
      - "cognite/powerops/resync/v1/**.py"
      - "cognite/powerops/cli.py"
      - "resync/**.yaml"
      - "resync/**.yml"

env:
  PYTHON_VERSION: "3.11"
  CLIENT_CONFIG_FILE: "power_ops_config.yaml"
  CONFIGURATION_FILE: "resync/configuration.yaml"

jobs:
  resync-plan:
    name: Resync Plan "v1" to CDF project ${{ vars.PROJECT }}

    environment:
      name: CI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip poetry==1.*
          poetry config virtualenvs.create false
          poetry install

      - name: Run resync plan
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          PROJECT: ${{ vars.PROJECT }}
          CLUSTER: ${{ vars.CLUSTER }}
          TENANT_ID: ${{ vars.TENANT_ID }}
        run: |
          echo Running resync plan in CDF environment $PROJECT
          powerops plan_v1 $CLIENT_CONFIG_FILE $CONFIGURATION_FILE
